### ISSUE TITLE
Ленивая загрузка фотографий

### ISSUE THREAD

**Issue by greeceruit** [nicothin/greeceru#11]
На странице результатов поиска 8 объектов недвижимости. У каждого может быть от 15 до 30 фотографий. В инструментах разработчика Google Chrome видно, что браузер загружает все эти фотографии при загрузке страницы. Может быть, имеет смысл применить какую-нибудь другую карусель, которая выводит только cover-фото, а остальные фотографии будет подгружать по мере необходимости, то есть при нажатии на стрелки вперёд-назад?

**Comment by greeceruit** [comment]
Сейчас, вроде, нашёл, что можно использовать owlCarousel с lazyLoad : true.  Попробую переделать...

**Comment by nicothin** [comment]
если не получится, отпишите тут
http://owlcarousel2.github.io/OwlCarousel2/demos/lazyLoad.html

**Comment by greeceruit** [comment]
Ленивая загрузка готова.
