### ISSUE TITLE
Страницы: Blog

### ISSUE THREAD

**Issue by vladimir075** [nicothin/greeceru#12]
Николай, @Evgeniygavr несколько дней в ограниченном доступе к интернету, поэтому возможно не сразу реагирует на наши вопросы. переживаю, чтобы при этом не простаивала наша работа, а также потом не приходилось ее переделывать и путаться. В рамках этого предлагаю, если образовывается временной пробел, переходить к трем страницам Blog, кажущимся мне наиболее простыми

**Comment by nicothin** [comment]
ok.
Итого, на данный момент план:

1. доделать стр. regions
2. блоговые страницы
3. страница конкретной локации

**Comment by vladimir075** [comment]
а "страница конкретной локации" это у нас что?

**Comment by nicothin** [comment]
05 - internal property.psd

**Comment by vladimir075** [comment]
можно скриншот? ) я в инвижион смотрю )

**Comment by nicothin** [comment]
![image](https://user-images.githubusercontent.com/3499680/27080853-7f2634b0-5046-11e7-8852-bb53e3cc6e40.png)

Есть вопрос по адаптивности страницы со списком постов в блоге: как она ведет себя между 480 и 1600? Пока делаю так же, как последние записи на главной.

**Comment by Evgeniygavr** [comment]
С блогом да, центрируйте карточки новостей  как сделали ранее на главной

**Comment by nicothin** [comment]
https://nicothin.github.io/greeceru/blog.html — страница списка записей (сделаю страницу отдельной записи, дам ссылку тут же)

добавил поведение на 1440+ — модульная сетка по 3 в ряд (плохо смотрелось с 2 в ряд).
посмотрите в дапазоне 768-1439 — может, там сделать что-то более «резиновое», а от центровка не очень то сочетается с заголовком и пагинатором.

**Comment by vladimir075** [comment]
@Evgeniygavr прошу утвердить, либо прокомментировать необходимые поправки

**Comment by Evgeniygavr** [comment]
Мне необходимо увидеть, чтобы что-то сказать. Можно ссылку?

**Comment by vladimir075** [comment]
ссылка на верстку выше, и вопросы Николая.
Дублирую 
https://nicothin.github.io/greeceru/blog.html
"добавил поведение на 1440+ — модульная сетка по 3 в ряд (плохо смотрелось с 2 в ряд).
посмотрите в дапазоне 768-1439 — может, там сделать что-то более «резиновое», а от центровка не очень то сочетается с заголовком и пагинатором."
(лично мне кажется не критично, если я конечно понял о чем речь. Но я плохо разбираюсь в разрешениях экранов и может смотрел не на то)

**Comment by Evgeniygavr** [comment]
Давайте попробуем с экрана меньше чем 1439 заменять первую статью, с большой фоткой, на маленькую плитку. Тогда, я так думаю, плиток станет три в ряд. А с последующим брейкпоинтом станет две плитки в ряд и на мобильных уже одна плитка, как есть в макете. Реально такое сделать?

Центрирование, согласен, выглядит бредово. Лучше оставить выравнивание контейнера со статьями по левому краю. Как есть сейчас на разрешениях 1600 до 1439.

**Comment by nicothin** [comment]
C 1440 до 1600 нет выравнивания по левому, блоки занимают 100% доступной ширины с центровой родителя (внутри родителя в данном случае и заголовок, и пагинатор).

В общем, убрал центровку, немного поменял модульнную сетку. Теперь хорошо смотрится, только поменялись необходимые пиксельные размеры картинок: большая картинка д.б. 970, малая 470 (ширины). Это я на заметку @greeceruit :)

**Comment by vladimir075** [comment]
@Evgeniygavr @greeceruit Если нет вопросов и замечаний, давайте утвердим верстку страницы https://nicothin.github.io/greeceru/blog.html

**Comment by Evgeniygavr** [comment]
Да, с блогом заканчиваем

**Comment by vladimir075** [comment]
Данная страница утверждается.

**Comment by nicothin** [comment]
https://nicothin.github.io/greeceru/blog-post.html — страница отдельной записи

**Comment by vladimir075** [comment]
У меня, вроде, нет замечаний. Не знаю, как у @Evgeniygavr

**Comment by Evgeniygavr** [comment]
Все ок.
