### ISSUE TITLE
Страница FAQ

### ISSUE THREAD

**Issue by vladimir075** [nicothin/greeceru#13]
Коллеги, к вопросам на странице FAQ, я бы хотел иметь возможность добавлять видео с ютуба (в каких то темах оно будет, в каких то - нет). При работе над макетами такой задачи не стояло, потому там его нет. 
Самый простой вариант это добавлять в тексте вопроса ссылку Watch video и открывать видео в ютубе в новой вкладке. Для этого ничего в верстке делать не надо.
Второй вариант - это раскрывать окно видео на самой странице при нажатии на ссылку watch video в тексте.
Третий вариант - изначально показывать и текст и видео при открытии конкретной темы вопроса, если видео имеется в наличии. 
В случае выбора второго или третьего вариантов, наверное Николаю необходимо будет предусмотреть это при верстке. 
Вопрос к Евгению, какой из трех вариантов предпочтительней с точки зрения дизайна и юзабилити @Evgeniygavr

**Comment by vladimir075** [comment]
может имеет смысл заголовки разделов вывести в сайдбар? а то топиков там предполагается много. чтобы удобней было пользоваться

**Comment by nicothin** [comment]
вариант с видео в тексте ответа не требует с моей стороны никаких доп. усилий.
вариант с модальным — требует, но небольших.

**Comment by Evgeniygavr** [comment]
Если видео будет немного, то можно расположить его прямо в тексте. Николай уже сделал стиль для видео вставок. Если видео будет больше чем 3-5, то лучше показывать в pop-up окне. Стиль этого окна следует взять из макета карточки объекта, в котором показываются доп. фотографии.

Идея кликов по ссылке берем здесь - http://help.dribbble.com/#what-is-dribbble Нажал - перекскролило к нужному разделу, только если можно прошу сделать чуть плавную анимацию.

Выносить разделы в сайдбар не нужно. Контекстная часть у нас слева.

**Comment by vladimir075** [comment]
1) Видео предполагаю больше 3-5, так что делаем тогда в модальном по рекомендации @Evgeniygavr 
 2) @nicothin прошу учесть поведение раскрытия топика, согласно описанному Евгением выше
3) про сайдбар будем послушны дизайнеру ))

**Comment by vladimir075** [comment]
сайдбар, тот который есть (subscribe), я так понимаю, в десткопе приклееный

**Comment by Evgeniygavr** [comment]
На этой странице - да т.к. высота блочка подписки влазит в экран и можно сделать, чтобы он следовал (скролился) за пользователем.

**Comment by nicothin** [comment]
Итого:

- при клике на ссылке плавный скролл к нужному месту — ok
- видео показывать в каком-то поп-апе (модальном окне, все-таки?), которого я не вижу в макете: 
![image](https://user-images.githubusercontent.com/3499680/27179515-a2702baa-51d7-11e7-8c8f-faa73872242f.png). Дайте макет. Дайте внешний вид того, на чем нужно кликать, чтобы появлялся этот пап-ап/модальное окно — не ясно как будут выглядеть вставки видео в тексте FAQ.
- блок subscribe в сайдбаре должен оставаться фиксированным во вьюпорте при скролле, пока его нижняя граница не доехала до подвала (на некоторых ширинах подвал высокий) — это только JS, оставляю это @greeceruit, ибо сам буду делать довольно долго.

**Comment by Evgeniygavr** [comment]
Обновлю макет с карточкой объекта чуть позже. Там ничего сверхъестественного нет - видео с фоном и иконка закрытия. 

"на чем нужно кликать" - синяя ссылка в тексте.

**Comment by vladimir075** [comment]
Николай, а почему в скриншот старница карточки объекта? Мы же ее отложили и сейчас обсуждаем страницу FAQ?
![screen shot 2017-06-15 at 2 47 32 pm](https://user-images.githubusercontent.com/17883276/27179954-aa76e440-51d9-11e7-8032-77be7129079a.png)

https://projects.invisionapp.com/share/2MBJ7MQ68#/screens/234643665

**Comment by Evgeniygavr** [comment]
Потому что я написал, что в том макете стиль для поп-ап окна, потому там скришот.

**Comment by vladimir075** [comment]
а, сорри

**Comment by nicothin** [comment]
1 скролл — ok
2 макет — жду

**Comment by Evgeniygavr** [comment]
Обновите, пожалуйста, [макет](https://drive.google.com/drive/folders/0B95Z4pk0LfjgSnBVdnlkNV9RTlU?usp=sharing) - 05 - internal property.psd

Еще раз про механику: в тексте будет [синий линк](#), по клику открываем окно.

**Comment by nicothin** [comment]
https://nicothin.github.io/greeceru/faq.html

**Comment by Evgeniygavr** [comment]
Класс, только в pop-up уберите, пожалуйста, заголовок.

**Comment by Evgeniygavr** [comment]
Хотя этот же заголовок уберется и на мобильном... Тогда нет, пусть будет.

**Comment by vladimir075** [comment]
мои замечания - 
- десктоп 1) сайдбар не приклеен (сафари, хром) 
2) окно попапа на мой взгляд открывается очень сильно к верхнему краю экрана. Может сделать чтобы чуть пониже открывалось? а то выше уровня взгляда получается.
- по мобил замечаний нет

**Comment by nicothin** [comment]
>десктоп 1) сайдбар не приклеен (сафари, хром)

выше я писал:
>блок subscribe в сайдбаре должен оставаться фиксированным во вьюпорте при скролле, пока его нижняя граница не доехала до подвала (на некоторых ширинах подвал высокий) — это только JS, оставляю это @greeceruit, ибо сам буду делать довольно долго.

могу попробовать сделать и сам, но времязатраты малопредсказуемы, т.к. я не знаю как поведет себя соотв. бутстраповский компонент.
делать?

>окно попапа на мой взгляд открывается очень сильно к верхнему краю экрана. Может сделать чтобы чуть пониже открывалось? а то выше уровня взгляда получается.

сделал ниже (не сильно, ибо мы не знаем высоты вьюпорта)

**Comment by vladimir075** [comment]
по первому сорри, забыл ) пусть делает @greeceruit 
по второму ок
к чему переходим? там страницы блога остались внутренние, да?

**Comment by nicothin** [comment]
если эту удвердите, то далее — внутренняя блоговая и простенькая mortgage

**Comment by vladimir075** [comment]
да, эту утверждаем )

**Comment by vladimir075** [comment]
Блоговых там две вариации - открытыми комменатми и скрытыми ) и в обеих видео, на всякий случай )
после блога и mortgage предлагаю перейти к стадиям занесения объекта недвижимости List property

**Comment by vladimir075** [comment]
Прошу в странице Faq добавить голубой значек стрелочки наверх, который может перебрасывать юзера вверх списка (в макетах не было)

**Comment by nicothin** [comment]
Не понял где и как должны выглядеть, добавил две работающие кнопки со стрелками вверх внизу обеих больших секций вопросов.
