### ISSUE TITLE
Страница: Карточка объекта недвижимости

### ISSUE THREAD

**Issue by vladimir075** [nicothin/greeceru#14]
Николай, по по очередности работы, предлагаю отложить на несколько дней страницу 05 - internal property.psd, (которой предлагаю дать термин "страница карточки объекта недвижимости" или Property card). Дело в том, что их будет две вариации - одна объект продажи, одна объект аренды. В целом они почти одинаковые но все же с небольшими вариациями. К концу недели Евгений обещал отрисовать небольшую правку под карточку объекта на аренду и мы окончательно утвердим обе вариации. 
Сверстать по очередности можно простую страничку FAQ, потом например перейти к стадиям занесения объекта недвижимости (List property). Конечно по последним лучше предварительно получить необходимые комментарии механики от @Evgeniygavr 
(ЛК делать будем в последнюю очередь).

**Comment by nicothin** [comment]
ok, эту страницу пока отложили.
У меня на очереди страница отдельной записи в Блоге (почти сделал разметку, завтра простилизую). Потом возьму FAQ.
