### ISSUE TITLE
Страницы List property

### ISSUE THREAD

**Issue by vladimir075** [nicothin/greeceru#15]
@Evgeniygavr прошу сделать разъяснения для Николая по механике страниц занесения объекта недвижимости, если считаешь что в каких то из них есть такая необходимость
(не знаю может здесь следует как то разбить issue, @nicothin виднее как тут организовать лучше)

**Comment by nicothin** [comment]
Буду отчитываться «поэкранно» для этой группы страниц.
https://nicothin.github.io/greeceru/list-property-0.html — нулевая страница в обычной обертке (для прочих шапка и подвал отличаются)

**Comment by nicothin** [comment]
Вопрос для @Evgeniygavr 
В мобилке остается бургер главного меню, в широкой версии главное меню заменено на «хлебные крошки». Это норм? Главное меню получается доступно юзеру только на узком вьюпорте?

**Comment by vladimir075** [comment]
у меня замечаний нет.
@Evgeniygavr ?

**Comment by Evgeniygavr** [comment]
Мне кажется, что бОльшее количество людей будет вносить объект с десктопа, поэтому не хочется, чтобы они "уходили" с этой страницы. Давайте пока оставим все как в макетах. 

Замечаний по первому шагу нет.

**Comment by vladimir075** [comment]
@nicothin честно говоря я не очень понял в чем была суть вопроса. Если можно скрин с пояснением, буду благодарен

**Comment by nicothin** [comment]
Вопрос 2
http://take.ms/l71FH — этот блок с кнопками фиксирован во вьюпорте (по нижнему краю), но «подвал» не фиксирован — когда страница доскроллится вниз (или в отсутствие скролла), блок с кнопками закроет собой подвал.
Убираем подвал?

Вопрос 1, переформулировка
Сравните дизайн для мобилок и для настольных.
В мобильной версии есть доступ к главному меню (бургер), в настольной нет (вместо меню — строка с описанием шагов и положения посетителя на конкретном шаге)

**Comment by nicothin** [comment]
https://nicothin.github.io/greeceru/list-property-step-1.html — шаг 1 (обертка и кнопки) с демонстрацией проблемы, описанной в вопросе 2

**Comment by Evgeniygavr** [comment]
Слушайте, давайте вообще уберем с этих страниц футер и тогда проблемы не будет. 

ps. Дождемся решения от Владимира.

**Comment by vladimir075** [comment]
я не против убрать футер, если @Evgeniygavr не против этого решения

**Comment by nicothin** [comment]
Если закрепить выше футера, то если есть большой верт. скролл и не видно футера, будет «дырка» между нижним краем блока кнопок и нижней границей вьюпорта (место, предусмотренное под футер) )))
Да, убрать футер было бы максимально простым и быстрым решением.

Другой вариант — прибить футер ко вьюпорту. Хреновый вариант, т.к. занимаем критически нужное место по вертикали блоком (футером), который не нужен юзеру на этой странице.

**Comment by nicothin** [comment]
Футер уберу.

**Comment by vladimir075** [comment]
ок

**Comment by nicothin** [comment]
![image](https://user-images.githubusercontent.com/3499680/27388013-e5673000-56a2-11e7-94c5-33a43b1587e7.png)
проблема: вкладки-табы под заголовком на 480 смотрятся неплохо, пока слова английские короткие, но на более узких ширинах точно не станут в одну строку.
предположительно, буду убирать слово services на узких экранах

**Comment by vladimir075** [comment]
Я не против

**Comment by nicothin** [comment]
https://nicothin.github.io/greeceru/list-property-0.html — нулевой
https://nicothin.github.io/greeceru/list-property-step-1.html — затравка шага 1
https://nicothin.github.io/greeceru/list-property-step-1-sale.html — шаг 1 целиком (все, кроме первого блока выделяются кликом, первый блок выделяется кликом по Accept)

**Comment by nicothin** [comment]
https://nicothin.github.io/greeceru/list-property-step-2.html
https://nicothin.github.io/greeceru/list-property-step-2-map.html
Шаг 2

**Comment by nicothin** [comment]
шаг 3
https://nicothin.github.io/greeceru/list-property-step-3.html
https://nicothin.github.io/greeceru/list-property-step-3-has-photos.html — добавил фото разных пропорций, миниатюры ограничил по размеру (и по горизонтали, и по вертикали)
https://nicothin.github.io/greeceru/list-property-step-3-form.html — там часть подписей к полям по дизайну выходят за границы габаритов полей (http://take.ms/1VlCS), я сделал их однострочными, но это потенциальная проблема переполнения, придется следить за длиной текста там.

**Comment by vladimir075** [comment]
Шаг 1
1) https://nicothin.github.io/greeceru/list-property-0.html здесь футер нужен разве
2 ) https://nicothin.github.io/greeceru/list-property-step-1-sale.html view sample открывает попап - чтобы не забыть)

**Comment by vladimir075** [comment]
Шаг 1 мобил, айфон 6
1) 
![img_5592](https://user-images.githubusercontent.com/17883276/27515629-c89e4dbc-59b0-11e7-80c5-67b4a24c0b6e.PNG)
@Evgeniygavr нормально или лучше увеличить кнопку продажи?

**Comment by vladimir075** [comment]
Шаг 1 мобил, айфон 6
![img_5593](https://user-images.githubusercontent.com/17883276/27515641-ee1cd108-59b0-11e7-8d6f-0a7de203bc03.PNG)
заезжает нижний край за кнопки (у нас такая проблема уже была в другом месте)

**Comment by vladimir075** [comment]
Шаг 1 мобил, айфон 6
крестики нолики ломаются )) кстати здесь будем делать, чтобы крестик снимался (отменялся) или только по шагу назад ? По идее крестик должен иметь функцию отмены при нажатии
(при этом базовые функции отменить нельзя, а вот дополнительные можно)

![img_5594](https://user-images.githubusercontent.com/17883276/27515665-549e3462-59b1-11e7-851c-efdbcb3eeb1e.PNG)

**Comment by vladimir075** [comment]
https://nicothin.github.io/greeceru/list-property-step-2.html убрать поле state

**Comment by vladimir075** [comment]
https://nicothin.github.io/greeceru/list-property-step-2-map.html
1) В десктопе маркер должен перетаскиваться, а в мобиле хорошо если будет двигаться сама карта, как под маской, а маркер визуально остается по центру. 
Эти оба вопроса уже относятся к программированию или что-то надо делать в верстке?

**Comment by vladimir075** [comment]
https://nicothin.github.io/greeceru/list-property-step-3-form.html
1) убрать селектор валют рядом с ценой, оставить только значек евро. Выбора там не будет
2) в дропдаун листы может надо постаить по умолчанию слово select (до нажатия на стрелку)?

**Comment by vladimir075** [comment]
https://nicothin.github.io/greeceru/list-property-step-3-form.html
Здесь также следующая проблематика. существуют разные категории объектов недвижимости и в зависимости от выбираемой сверху категории меняются поля ниже для заполнения. Например для выбранного вариант "квартира" появляются поля "жилая площадь", "количество ванных", итд а для категории "участок" таких полей к заполнению не появляются, появляются другие. Все возможные варианты @Evgeniygavr не отрисовывал. 
Как правильнее поступить в данном случае? Сделать мне список всех возможных полей для всех вариантов категорий недвижимости, вывести их и предусмотреть их блокирование программистом? Это то что, для предотвращения проблем с отображением верстки, если я правильно понял, предложил @greeceruit 
Да и честно вводом параметров я сейчас смотрю, не очень доволен, какой то он немного беспорядочный, мне кажется не очень удобный для юзера. Или мне так кажется?
 @Evgeniygavr @nicothin, что скажете свежим взглядом?

**Comment by nicothin** [comment]
проблема ширины кнопки — ждем решения @Evgeniygavr 
проблема высоты блока — аналогично
сломавшиеся кнопки в мобильном модальном окне — поправил

>https://nicothin.github.io/greeceru/list-property-step-2.html убрать поле state

убрал

> В десктопе маркер должен перетаскиваться, а в мобиле хорошо если будет двигаться сама карта, как под маской, а маркер визуально остается по центру.
Эти оба вопроса уже относятся к программированию или что-то надо делать в верстке?

да, это JS

>убрать селектор валют рядом с ценой, оставить только значек евро. Выбора там не будет

поменял

>в дропдаун листы может надо постаить по умолчанию слово select (до нажатия на стрелку)?

добавил

>Здесь также следующая проблематика. существуют разные категории объектов недвижимости и в зависимости от выбираемой сверху категории меняются поля ниже для заполнения. Например для выбранного вариант "квартира" появляются поля "жилая площадь", "количество ванных", итд а для категории "участок" таких полей к заполнению не появляются, появляются другие. Все возможные варианты @Evgeniygavr не отрисовывал.

http://take.ms/CACsc — я набираю форму по БЭМ как из кирпичей, могу набрать по описанию, если нужно.
пока не делаю, ибо это время.

**Comment by nicothin** [comment]
@Evgeniygavr вопрос: есть ли в векторе http://take.ms/E7DQ2 — эти картинки?

**Comment by Evgeniygavr** [comment]
1. Кнопки. Не совсем понимаю почему такое произошло, но кнопки должны быть одинакового размера. Если требуется, то увеличиваем "sale", а текст "or" переносим вниз.
"Sell"
or
"Rent"

2. Иконки - [залил](https://goo.gl/AwmzPE)

**Comment by vladimir075** [comment]
такое происходит потому что по английски "сдать" это "rent OUT", что длиннее слова sell. (просто Rent  это снять). Посему предлагаю увеличить просто по длине кнопку sell и между ними разместить "or", как выше предложил Евгений

**Comment by nicothin** [comment]
Кнопки и or — сделал до 767 включительно так, чтобы кнопки имели минимальную ширину 230 пикс, а or был на отдельной строке. С 768 и далее — встают в строку, по кр. мере для английского.
Иконки плана, кровати, ванной и total — это только формат svg, внутри там растр, а не вектор )) Пока оставил растром в png-формате.

https://nicothin.github.io/greeceru/list-property-step-4.html — шаг 4
https://nicothin.github.io/greeceru/list-property-step-5.html — шаг 5
https://nicothin.github.io/greeceru/list-property-step-6.html — ясно

жду правок/приемки и данных о том, какую страницу пилить далее.
если макеты обновлялись, прошу ссылку на обновленный макет страницы, которая далее по плану должна увидеть свет.

**Comment by vladimir075** [comment]
если иконки нужны в другом формате, @Evgeniygavr прошу предоставить

**Comment by nicothin** [comment]
Формате — нет, формат SVG — то, что нужно. Однако, нужно, чтобы внутри SVG был вектор, а не растр )))

**Comment by vladimir075** [comment]
значит прошу @Evgeniygavr предоставить растр )))
@nicothin по верстке выше вроде замечаний нет. Единственное если не сложно на странице https://nicothin.github.io/greeceru/list-property-step-6.html в самом низу уже под боксом сделать небольшую полоску мелкого серого шрифта lorem ipsum. Там мы напишем что мы вышлем им чек по мейлу (этого не было в дизайне).

**Comment by Evgeniygavr** [comment]
Обновил [иконки](https://goo.gl/AwmzPE)

**Comment by nicothin** [comment]
Серую строку текста добавлю, придет при следующем деплое (сегодня вечером).
Иконки прыгают по размерам, но это я поправлю ))

**Comment by nicothin** [comment]
Иконки сменил на векторные.

**Comment by greeceruit** [comment]
На странице http://www.nomesitis.gr/list-property-for-sale/
если не отмечена галочка Accept в блоке "Listing your property to greece.ru", кнопка Proceed в правом нижнем углу должна быть disabled. Я нашёл закоментированный span для мобильной версии неактивной кнопки Proceed, поменял класс span'а на layout-text__btns-desktop-item--disabled. @nicothin , у вас предусмотрен какой-то класс для неактивной кнопки proceed в desktop версии вёрстки?

**Comment by greeceruit** [comment]
Прошу прощения. Последний вопрос снимается. Нашёл disabled кнопку на list-property-step-3-form.html

**Comment by vladimir075** [comment]
Вот на этой странице https://nicothin.github.io/greeceru/list-property-step-1-sale.html при попытке выбора Additional Services, если юзер предварительно не выбрал в дропдауне регион, хорошо если дропдаун региона будет загораться красным (при этом сервис не загорается синим до выбора региона). @greeceruit вроде это может добавить сам, если @nicothin подскажет классы, или как там это называется. Николай, можете подсказать Олегу, что ему для этого надо?

**Comment by nicothin** [comment]
класс `field-drop-checkboxes--error` можно дописать на элементе с классом `field-drop-checkboxes` (это обертка дропа) и там будет стиль как у ошибочного поля ввода — красная рамка и красный цвет текста
(в разметке я сейчас дописал этот класс в комменте)

**Comment by greeceruit** [comment]
Имеются вопросы по странице https://nicothin.github.io/greeceru/list-property-step-3.html
Как будем делать функционал? Есть два варианта. 

Первый
Сразу начинаем отправлять фотографии на сервер. И только после загрузки всех фотографий, показываем юзеру страницу https://nicothin.github.io/greeceru/list-property-step-3-has-photos.html, где он сможет определить последовательность фотографий, назначить cover-фото и удалить лишние. Но тогда не хватает прогресс-индикатора процесса загрузки. 

Второй.
Показываем юзеру превьюшки всех фотографий до их загрузки на сервер.   В этом случае должна быть кнопка uoload photos

Второй вариант мне кажется, как минимум, более логичным. Этим способом я пользуюсь для пакетной загрузки фотографий из админки (с помощью виджета plupload, который ещё и сжимает фото на стороне клиента).  
![screenshot from 2017-07-19 17-52-54](https://user-images.githubusercontent.com/29063417/28373610-7540bf5c-6cab-11e7-89b4-58dca321c45f.png)

**Comment by vladimir075** [comment]
думаю это вопрос также к @Evgeniygavr, поскольку для вышеописанных обоих вариантов не хватает элементов дизайна. При этом второй вариант в принципе думаю более логичен (клиент кидает фотки, видит их превью, отбирает и и удаляет ненужное, и только после этого  загружает сервер работой по загрузке отобранных фоток)

**Comment by vladimir075** [comment]
@Evgeniygavr Жень, есть более простое волевое решение, на которое нам надо благословение дизайнера. Кроме того что я описал выше, у @greeceruit возникают сложности с полной стилизацией готового аплоадера фоток. Если писать свой - займет уйму времени. 
Простое решение, требующее при этом чуть чуть пожертвовать дизайном, заключается в следующем.
Шаг первый - юзер видит на странице https://nicothin.github.io/greeceru/list-property-step-3.html вместо картинки 
![screen shot 2017-07-19 at 6 27 34 pm](https://user-images.githubusercontent.com/17883276/28375689-ca8f4a3c-6cb0-11e7-9c22-26f452a0cbb5.png)
картинку 
![screen shot 2017-07-19 at 6 27 16 pm](https://user-images.githubusercontent.com/17883276/28375709-dc956f2c-6cb0-11e7-9127-7ea4d4c44715.png)
(т.е. заменяется серое поле. при этом "разноцвет" рядом с надписью Select в левом верхнем углу можно заменить)
Далее туда встают превью фоток и юзер выбирает что загружать. После загрузки он опять видит наш дизайн без проблем вот в этом виде  https://nicothin.github.io/greeceru/list-property-step-3-has-photos.html
Если он нажмет еще раз аплоад, чтобы добавить еще фото, то опять увидит этот сторонний аплоадер.
Это значительно сэкономит нам время реализации. Даешь добро, Жень?

**Comment by vladimir075** [comment]
(если брать это решение, то там уже есть и прогресс бар и прочее - ничего рисовать также не понадобится)

**Comment by greeceruit** [comment]
С виджетом plupload тоже, к сожалению, не всё так просто. 
http://www.nomesitis.gr/list-property-photos/?deal_type=1
@nicothin , можно ли как-то подружить этот ui-виджет с нашей вёрсткой?

http://www.plupload.com/examples

**Comment by nicothin** [comment]
Думаю, смогу подружить.
Плюс, наверняка смогу привести в какое-никакое, а соответствие дизайну, ибо сейчас там все «в лучшем стиле нулевых». Пошлая веб-два-нольность из всех щелей.

**Comment by nicothin** [comment]
Стили плагина включу в сборку — минус одно соединение при загрузке.

**Comment by nicothin** [comment]
В работающей версии к странице подключен ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/base/jquery-ui.css
Исхожу из того, что в продакшене его не будет.

**Comment by vladimir075** [comment]
если подружить а еще и подвести в соответствие дизайну можно, то отлично

**Comment by nicothin** [comment]
Дело несколько осложняется тем, что для работы этого загрузчика нужно подгружать:

- jquery 1.9 (в сборке уже есть версия 3)
- ВЕСЬ jquery UI (в сборке частично есть — ползунки выбора ипотеки в сайдбаре на нем работают)

простилизовать и упростить до очень напоминающего наш дизайн, уверен, смогу.
@greeceruit @vladimir075 делать?

**Comment by greeceruit** [comment]
Мне-то нравится. Такой вариант будет реализован с моей стороны быстрее. Выкинуть виджет и оставить только plupload API и самому обрабатывать все события - будет существенно дольше.

**Comment by nicothin** [comment]
ok, стилизую.

**Comment by vladimir075** [comment]
@nicothin сколько у Вас это может занять времени примерно?

**Comment by nicothin** [comment]
Час-полтора

**Comment by vladimir075** [comment]
Да, @nicothin прошу сделать. С учетом того, что мы его подгоняем и под наш дизайн, видимо вопрос к @Evgeniygavr на данном этапе, снимается

**Comment by nicothin** [comment]
Считаю тогда, что стили и скрипты jqueryUI будут подключены.
При вожу к виду, показанному в дизайне.

**Comment by vladimir075** [comment]
Николай, можем сейчас созвониться в скайпе?

**Comment by nicothin** [comment]
Задеплоил смену стилей: http://take.ms/bfwHF
Посмотреть это на https://nicothin.github.io/greeceru/list-property-step-3.html не получится — запросы за файлами по http блокируются (пропускает только https, по этому протоколу подключенные файлы недоступны), так что ждем деплоя на http://www.nomesitis.gr/list-property-photos/?deal_type=1 — посмотреть вживую, а мне еще и достилизовать интерактивные состояния (процесс загрузки, факт загрузки).
Убрал из сборки компонент field-multifile (серый прямоугольник для добавления файлов).

п.с.: изменения размера канваса, отрисовывающего миниатюру в настройках плагина не нашел, так что пока просто растягиваю этот канвас до 160 по ширине. Он всегда горизонтальный, даже если фото вертикальное — особенность плагина, видимо.

**Comment by vladimir075** [comment]
Коллеги, представленный Николаем вариант меня по дизайну устраивает, и хотя он имеет слабые отклонения от дизайна, думаю Евгений на нас не будет ругаться )) НО! Упомянутая Николаем проблема горизонтальности является даже более серьезной, чем вопрос размера превью. Я сейчас работаю с этим плагином по модерации/замене фоток существующих в базе объектов и действительно вертикальные фотки представляются в превью горизонтальными, при чем тупо с обрезкой верха и низа. Я просто удаляю как правило такие превью. Но я работаю с большим объемом фоток и у меня есть и горизонтальные и вертикальные на выбор. А вот подобная обрезка у юзеров для меня видится проблемой посерьезней. @greeceruit, какие соображения?

**Comment by greeceruit** [comment]
@vladimir075 , @nicothin 
http://www.nomesitis.gr/list-property-photos/?deal_type=1

Вроде, работает. Только прогресс-индикатор сломанный. Но может быть , что только у меня в Хроме под ХР. Часа через 2 посмотрю на Убунту 16.04

**Comment by vladimir075** [comment]
Замечания следующие
1) Остается проблема с показом превью чуть больше, при этом не размывая их.
2) остается проблема с обрезкой плагином вертикальных фоток в превью. проблема важная
3) прогресс индикатор у меня тоже из верстки вылезает
![screen shot 2017-07-20 at 4 01 31 pm](https://user-images.githubusercontent.com/17883276/28418715-6574acc2-6d65-11e7-9d81-bd0a65c88acd.png)
4) Если бросить несколько превью в поле загрузки, но не начать еще их загружать есть надпись files qued,  но нигде нет надписи добавить еще фотки в загрузку (в очередь загрузки)
5) после загрузки вылезает такой попап. Вообще попапом должно что-то вылезать по окончании загрузки?
![screen shot 2017-07-20 at 4 02 24 pm](https://user-images.githubusercontent.com/17883276/28418825-d7e20778-6d65-11e7-92f5-d5c8ee4e785f.png)
6) раз уж стилизация Николаем сделана, то надо будет привести в полное ей соответствие 
![screen shot 2017-07-20 at 4 11 17 pm](https://user-images.githubusercontent.com/17883276/28419006-6b92744e-6d66-11e7-8210-ea5220581986.png)

**Comment by greeceruit** [comment]
Попап остался по наследству от fu - он уберётся. Про размеры превьюшек я кое-что нашёл.  Поэкспериментировать. Про фотки с вертикальной ориентацией -

**Comment by nicothin** [comment]
отклонения от того, что я сделал значительные.
@greeceruit прошу убрать подключение www.nomesitis.gr/static/css/jquery.ui.plupload.css — он портит картину.
Правда, отчего-то, и без него нет соответствия моему скрину, сейчас разберусь.
п.с.: прогресс и должен был быть сломан, я ж его не делал еще — ждал внедрения работающей версии.

**Comment by nicothin** [comment]
Добавил правки для прогресса и некоторые другие стилевые глюки подправил в этом компоненте.
Поскольку работаю не с живой версией, а с ее копией, возможно еще несколько итераций для доведения до приемлемого вида.

**Comment by greeceruit** [comment]
@nicothin ,  www.nomesitis.gr/static/css/jquery.ui.plupload.css  я убрал. Последние css и js на сервер загрузил. Николай, если не сложно, не сжимайте, пожалуйста js, я иногда туда в целях отладки могу что-то дописывать

**Comment by nicothin** [comment]
ok, следующий и все прочие деплои будут содержать только конкатенированный js, без углификации.

**Comment by greeceruit** [comment]
@vladimir075, @nicothin 
Нашёл, как изменить размер превьюшек в plupload UI Widget. Уже внедрил на http://www.nomesitis.gr/list-property-photos/?deal_type=1 Поставил 200 на 150. Своими глазами вижу только изменение размера. Растягиваются ли картинки, ухудшается ли в связи с этим качество - не вижу. Кстати говоря, если поставить, например, 200 на 200 (в надежде что вопрос с вертикально-ориентированными фотографиями отпадёт сам по себе), то виджет их то ли кропит, то ли ресайзит с искажением - не вижу - пробую на не очень хорошем экране и с не очень хорошими фото. Возможны эффекты наложения наших совместных усилий... Поглядите, пожалуйста.

**Comment by vladimir075** [comment]
- увеличенный размер превью, насколько я вижу, не растягивает и не искажает картинки. Поэтому вопрос размера превью можно считать в этом ракурсе решенным.
- вертикальные фото в превью кропятся под горизонтальные и таким образом не дают юзеру представления о том, что он загружает. поэтому данный вопрос остается открытым.
- также при добавлении ряда фоток в превью лебел add files  меняется на 4files queued. То есть собственно говоря "добавить файлы" исчезает. Если юзер хочет добавить еще файлы (не драгенддропом), то он может запутаться куда нажимать. @greeceruit @nicothin как думаете, как лучше для юзера? может просто не менять лебел add files на количество пресью в очереди? какая ему разница сколько в очереди у него превьюшек стоит. а вот куда опять нажать чтобы еще туда фоток добавить это важно.

**Comment by vladimir075** [comment]
хотя по последнему вопросу сейчас вижу что лебел меняется после загрузки превью опять на add files. так что наверное можно оставить и так как есть.

**Comment by greeceruit** [comment]
@vladimir075 
Предлагается сделать превьюшки фоток в очереди на upload квадратными. Тогда юзеру будет понятнее, что это всего-навсего τhumbnails. Тем более, что в карусели на http://www.nomesitis.gr/en/property/16062914-apartments-posidius/ тоже квадратные миниатюрки
А ещё квадратные миниатюрки хороши тем, что они сгладят картину от очень разноразмерных фоток, которые будут пытаться грузить юзера

**Comment by vladimir075** [comment]
Николай, для страницы https://nicothin.github.io/greeceru/list-property-step-3-form.html на прошлой неделе я предоставил  @Evgeniygavr все вариации полей параметров в зависимости от типов недвижимости и видов сделки. Евгений обещал ко вторнику/среде облечь предоставленную мной в схематичном виде информацию в макеты, которые надо будет сверстать (мы где то выше уже обсуждали эту проблематику). Ждем Евгения. Параллельно в связи с этим у @greeceruit есть просьба к данным страницам. Олег, прошу изложить.

**Comment by nicothin** [comment]
Я тоже за квадратные миниатюры

>Ждем Евгения. Параллельно в связи с этим у @greeceruit есть просьба к данным страницам. Олег, прошу изложить.

@greeceruit что за просьба?
@Evgeniygavr дайте отмашку, когда (и какие) макеты пере-скачать.

**Comment by vladimir075** [comment]
@nicothin макеты вариаций страниц ввода параметров (в зависимости от типа сделки и вида объекта недвижимости) Евгений сегодня предоставил по ссылке https://drive.google.com/drive/folders/0B95Z4pk0LfjgSVJFd25Dc3g1Q00
У меня корректировки 1) В asking price рядом со значком евро убирается селектор (ввести цену можно будет только в евро 2) В карточке Land plot в случае чекания чекбокса Delineate border  должна открываться карта (по аналогу данной карточки в Терре.
Какие то пожелания к верстке данных страниц были у Олега. @greeceruit прошу изложить Николаю.
@nicothin сколько времени займет верстка этого набора страниц?

**Comment by greeceruit** [comment]
@nicothin 
Предполагаю что вёрстка будет реализована блоками - по одному блоку на один тип недвижимости. В зависимости от типа недвижимости виден будет только соответствующий ему блок, остальные скрыты. Наверное, нет необходимости плодить по целой странице на каждый тип недвижимости.  Это скорее мысли вслух на тот случай, если у вас, Николай, есть какие-то другие соображения на эту тему.  Меня беспокоит такая мысль. Юзер может ввести часть параметров, включая тип недвижимости, а потом изменить тип. И введённые поля, общие для первоначального и изменённого типа недвижимости не должны потеряться. Скорее всего мне придётся копировать данные из одного инпута в другой. Идеально было бы, если можно было каждому инпуту в зависимости от типа недвижимости выставлять видимость, и все видимые инпуты красиво бы перестраивались. Но почему-то мне кажется, что вряд ли удастся такого добиться, учитывая, что в последствии мы можем часть полей убрать или какие-то добавить.

**Comment by nicothin** [comment]
Разберусь со страницей добавления локации в профиле и возьмусь за эту задачу.

**Comment by nicothin** [comment]
В плане верстки страницы сложностей не вижу, там новых элементов не много.
Очень сильно смущают поля, названия которых ощутимо выступают за габарит поля: http://take.ms/MBQCi

В плане технической реализации — да, полагаю это верхний дроп (псевдоселект) и после него несколько оберток (видна та, которая соответствует выбранному пункту селекта), внутри которых разные поля (по реализации и модификации проще сделать синхронизацию введенных данных в несколько однотипных инпутов, чем по условиям выводить или не выводить некоторые из полей).

Часа за 3, думаю, справлюсь.

**Comment by vladimir075** [comment]
Будем конечно пытаться сокращать надписи, но над некоторыми придется сломать голову. Если есть какие то другие предложения... )
По технике с @greeceruit 
По времени ок

**Comment by nicothin** [comment]
Сложность: в формах встречаются иконки помощи (круг, вопр. знак внутри).
По умолчанию они не работают для ширин менее 1170. Включить их для более узких вьюпортов?

Формы сделал. Сейчас видна последняя: https://nicothin.github.io/greeceru/list-property-step-3-form.html
@greeceruit там много дивов подряд с ID, в ID я записал имена артбордов из макета, по ним понятно какая форма где. (и да, я никогда не стилизую по ID, так что их можно менять при желании).

**Comment by greeceruit** [comment]
@nicothin, с ID дивов всё понял. Спасибо!

С видимостью иконок помощи на ширинах < 1170 - требуется политическое решение @vladimir075

**Comment by nicothin** [comment]
Не с видимостью иконок, но с работой их попапа вопрос.
Начально попапы встречалась только в малой карточке локации (наведение на иконки в нижнем ряду) и по просьбу @vladimir075 я их включил только начиная с ширины 1170 (в бОльшую сторону).

**Comment by greeceruit** [comment]
@nicothin , немного не понятно, в чём проблема с функциональностью. Сейчас я попробовал уменьшить ширину вьюпорта и, действительно, хинты при наведении мыши на вопросики пропали. В чём именно проблема с функционалом? Невозможно сделать или так получилось исторически в ходе правок?

**Comment by vladimir075** [comment]
https://nicothin.github.io/greeceru/list-property-step-3-form.html из asking price прошу убрать селектор рядом со значком евро. Занести можно будет только в евро.

**Comment by nicothin** [comment]
Исторически. Сделать, конечно, можно. Это ж обычный бутстраповский компонент.
Селектор у цены уберу.

**Comment by nicothin** [comment]
С тултипами разобрался — оказывается, у меня там уже есть специальный класс для активации этих бутстраповских тултипов без проверки ширины вьюпорта.
Включил тултипы на https://nicothin.github.io/greeceru/list-property-step-3-form.html для мобильных.

Дроп в блоке указания цены убрал.
