### ISSUE TITLE
Блок авторизованного посетителя в шапке

### ISSUE THREAD

**Issue by nicothin** [nicothin/greeceru#17]
Нужен макет с блоком авторизованного посетителя в шапке.
Для мобильной и настольной версий (если отличается).

**Comment by Evgeniygavr** [comment]
Размер аватарки можно посмотреть для десктопа в макете "06 - list property [step 1-2]", для мобилки - "[mobile] acc. edit".

Список пунктов меню, который отображается по клику, можно взять в макете ui,popup или же просто продублировать список из личного кабинета.
