### ISSUE TITLE
Дропы/селекты

### ISSUE THREAD

**Issue by nicothin** [nicothin/greeceru#18]
Хочу обратить внимание на потенциальную сложность: в дизайне есть много элементов с дропами: http://take.ms/bogGE
Сейчас я делаю их с помощью отдельного компонента, в дропе показываются чекбоксы (или радиокнопки, выглядящие как чекбоксы), поскольку тег `select` весьма ограничен в стилизации (а его дроп — так и вовсе не стилизуется кроссбраузерно).
Проблему вижу в том, чтобы при выборе какой-то опции писать ее название в основной области элемента (чтоб было видно, когда дроп закрыт)
@greeceruit как думаете, это проблема?
@Evgeniygavr @vladimir075

**Comment by greeceruit** [comment]
Да, уж.... Проблемка.... Причём, в форме занесения новой недвижимости не такая проблема, как в фильтре поиска. В дропбоксе выбора типа недвижимости должно быть что-то вроде "property type", что, скорее всего не поместится туда, где сейчас стоит "All". И, скорее всего, поведения должно быть два. Там, где выпадают чекбоксы, должно быть некое обобщающее название, например, beds или property type. А там где радиокнопки - выбранное значение. В случае с чекбоксами юзеру не понятно, выбрал ли он что-нибудь, или нет. Особенно в advanced search. То есть он может забыть, что он ограничил поиск только квартирами (то есть он не видит, какие чекбоксы отмечены и вообще отмечено ли хоть что-нибудь...). А кнопочки сброса условий фильтра у нас нет.  И если юзер отметил, например, чекбокс с большим кол-вом ванных, то он может ничего не найти с новыми условиями поиска. А нужна ли кнопка сброса - это вопрос к @vladimir075

**Comment by nicothin** [comment]
Проблема с фильтром теоретически решаема указанием в текстовой строке под фильтром нескольких «лейблов» с крестиками исключения справа.
Так же, пришло в голову, что можно поискать к-л плагин стилизации селектов, чтобы там был подменающий нативную выпадуху селекта DOM-узел, который можно было бы стилизовать — это решило бы проблему вынесения в основную область селекта (видимую в покое) выбранного пункта для случаев одного выбираемого пункта.

**Comment by vladimir075** [comment]
Чтобы окончательно не запутаться предлагаю разделить два вопроса. 
1) Дропы и селекты стадии занесения недвижимости (ввод).
2) Дропы и селекты фильтров поиска недвижимомсти (вывод)

Относительно ввода не вижу особой проблемы. На узких экранах можно делать дропы по одному в строку (по аналогу терры) @nicothin прошу подтвердить что этот вопрос не представляет проблем и закрывается

Относительно же вывода (фильтры поиска) есть вышеописанная проблема  в промежуточных разрешениях.
![screen shot 2017-06-26 at 7 46 39 pm](https://user-images.githubusercontent.com/17883276/27550466-7b9eb332-5aa8-11e7-8a67-6e1357993dcc.png)

Здесь а) можно продлить длину строки фильтров вправо на разрешениях где еще остается место
б) там где места уже не остается надо подумать что можно сделать

**Comment by nicothin** [comment]
И там, и там — ввод данных. И БЭМ-блок даже у меня один и тот же в обоих случаях )
Да, при заполнении формы проблемы с размером нет, есть только техническая сложность: с помощью JS нужно брать выделенный чекбокс и ставить его текст в видимую (в закрытом состоянии такого дропа) область — менять текст при выборе чекбоксов, в общем. (Сам это не сделал, памятуя, что большая часть JS — не моя епархия).

В фильтре есть проблема ширины, да. Как ее решать — не знаю.
