### ISSUE TITLE
Иконки

### ISSUE THREAD

**Issue by nicothin** [nicothin/greeceru#2]
@Evgeniygavr
Есть проблема с иконками: http://take.ms/hkQ8c — угол стрелки «полый». В макетах угол стрелки не имеет выреза.
Просьба прислать другую иконку, если «вырез» не нужен.

Размер иконки — 15×12 сейчас

**Comment by Evgeniygavr** [comment]
Странно, в макетах у меня такие стрелки без "дырок". Видимо при эскпорте в svg "что-то" случилось) Смотрю, что все такие стрелки с непонятными "дырками". Сейчас поправлю и отпишусь.

**Comment by Evgeniygavr** [comment]
Николай, а тупой вопрос - а если Вы все таки вставите такую стрелку на сайт, она тоже с "дыркой" отображается?

**Comment by Evgeniygavr** [comment]
Вот так они выглядят в макете у меня - http://joxi.ru/Dr8aPRjTNd1Gm6

**Comment by Evgeniygavr** [comment]
Поправил и обновил - [icons](https://drive.google.com/drive/folders/0B95Z4pk0LfjgZFpzRENyam5fMVU?usp=sharing)

**Comment by nicothin** [comment]
@Evgeniygavr иконка compare.svg не является векторной, внутри нее растр
пожалуйста, пришлите ее векторный вариант

**Comment by Evgeniygavr** [comment]
Oбновил - [icons](https://drive.google.com/drive/folders/0B95Z4pk0LfjgZFpzRENyam5fMVU?usp=sharing)
