### ISSUE TITLE
Страница Comparison chart

### ISSUE THREAD

**Issue by vladimir075** [nicothin/greeceru#20]
После страницы Internal property можно делать два Элемента функции compare
1) https://projects.invisionapp.com/share/2MBJ7MQ68#/screens/235788254
2) https://projects.invisionapp.com/share/2MBJ7MQ68#/screens/231713400

**Comment by nicothin** [comment]
Что-то второго элемента (малые карточки) в макетах не вижу :( 
Где смотреть? 
Как он выглядит на мобильных?
Где (на какой странице) его верстать?

**Comment by vladimir075** [comment]
@Evgeniygavr?

**Comment by Evgeniygavr** [comment]
Сравнение я не рисовал под мобильные. На карточках даже убраны были эти иконки. Сделал это из-за того, что сравнивать большое количество текста просто на просто неудобно на малых экранах.

**Comment by nicothin** [comment]
Что-то второго элемента (малые карточки) в макетах не вижу :(
Где смотреть?
Где (на какой странице) его верстать?

**Comment by Evgeniygavr** [comment]
Макет 01-home, search. В артборде, который называется home [hovers] есть скрытые группы, специально выделял их красным цветом. Группа, по-моему, называется comparison bottom.

**Comment by nicothin** [comment]
Макет 01-home, search
В артборде, который называется home [hovers] вижу только спрятанные в подгруппы группы, показывающие модальные окна.
Укажите путь к группе, показывающей 2-й элемент (горизонтальный блок с малыми блочками локаций) по названиям групп.

Для 1-го элемента, полагаю, нужно чтобы пункты сравнения «прилипали» левым краем к столбцу с названиями параметров?
Сам сделать такое смогу только добавлением слайдера в область прокрутки, что не очень хорошо, т.к. тогда пропадет скролл (можно добавить пагинатор).

Так же, неясно, что должен увидеть посетитель, уже находящийся на странице сравнения, если он сузит экран до мобильной ширины.

**Comment by Evgeniygavr** [comment]
Ну вот же эта полоска с объетами в макете 
<img width="1075" alt="2017-07-05 16 09 55" src="https://user-images.githubusercontent.com/28708246/27865766-8675734a-619c-11e7-89f3-015a5229d145.png">

Вот в макете, группа даже не скрыта была (compare bottm)
<img width="343" alt="2017-07-05 16 10 03" src="https://user-images.githubusercontent.com/28708246/27865782-920a50a4-619c-11e7-8023-69cacf9e70cc.png">

Если объекты начинают невлазить на плашку, то уже добавленные или новые помещяем в квадрат с цифрой (в скрине +6). Меньше размера 970px эту плашку вообще не показываем (на карточках при таком размере экрана нет иконок сравнения).

**Comment by nicothin** [comment]
Вижу, спасибо.

**Comment by nicothin** [comment]
https://nicothin.github.io/greeceru/compare.html

**Comment by nicothin** [comment]
а, стоп
крестики удаления на малый блок не добавил — заметил их сейчас в инвижане

**Comment by nicothin** [comment]
добавил, через минуту задеплоится

**Comment by vladimir075** [comment]
я бы попросил эелемент горизонтального скролирования сделать сразу видимым и со срелочкой, точно как на макете. 
![screen shot 2017-07-06 at 11 43 33 am](https://user-images.githubusercontent.com/17883276/27903144-e82b8436-6240-11e7-8bec-99515312da7d.png)

Иначе юзеру не очень понятно что он может там что-то горизонтально проскролировать.

**Comment by nicothin** [comment]
На винде с этим все хорошо — скролл видим сразу.
Для маков и линукса — только если какой-то JS-имитатор привязывать, поищу варианты.

**Comment by nicothin** [comment]
Использовал не JS-механизмы для сохранения нативного горизонтального скрола, сделал его видимым по умолчанию в подавляющем большинстве браузеров.

**Comment by greeceruit** [comment]
@nicothin , а с этой штукой https://projects.invisionapp.com/share/2MBJ7MQ68#/screens/231713400 уже есть вёрстка? Я так понимаю, что эта штука должна быть видна на всех страницах над футером? Или что-то вроде попап-окна, но не модального с абсолютным позиционированием?

**Comment by nicothin** [comment]
https://nicothin.github.io/greeceru/compare.html — вот тут этот блок снизу
как вести себя должна — не знаю, предположил, что просто висеть, прибитой в нижней границе вьюпорта, без поправок футера на ее присуствие.

**Comment by greeceruit** [comment]
@nicothin , @vladimir075 
Супер! Только напрашивается кнопка "закрыть", но такая, чтобы посетитель понимал, что закроется только окошко, а недвижимость, добавленная в compare, останется. Без возможности закрыть окошко, пользователь не видит часть футера, как минимум и лишается возможности там чего-нибудь кликнуть....

**Comment by vladimir075** [comment]
То, что он не видит часть футера меня не смущает, но функция закрытия, безусловно должна быть. Единственное предлагаю сделать ее не в виде кнопки, а в виде крестика в правом углу рядом с кнопкой Compare selected. Надо наверное только отделить этот крестик от кнопки  compare selected какой то серой черточкой

**Comment by nicothin** [comment]
проще всего так: http://take.ms/FRZ9J
плюсы: не нужно никуда сдвигать кнопку сравнения, визуально акцентирована за счет выступания из блока (перекликается с такими же элементами у предметов сравнения).

Другой момент, что если мы этот нижний блок скрыли, как он потом появится? При добавлении следующего предмета сравнения?

**Comment by vladimir075** [comment]
можно и так. @greeceruit для такого расклада от Николая что-то надо?

**Comment by vladimir075** [comment]
У нас есть мысль при закрытии этого дела через попап спрашивать не хочет ли он сохранить эти объекты в wishlist. 
При этом при добвлении нового объекта в compare ,  показывать и предыдущие добавленные до закрытия

**Comment by greeceruit** [comment]
@nicothin , @vladimir075 
Нужна только вёрстка полосы с добавленным крестиком закрытия.

**Comment by nicothin** [comment]
Минут 5 назад деплоил изменения для карты и иконки, вместе с этим пришло и требуемое тут изменение :)

**Comment by vladimir075** [comment]
@nicothin  
Когда я скролю страницу и потом хочу закрыть попап compare мне элемент скрола закрывает мне половину крестика закрытия. Через какое то время конечно элемент скрола исчезает, но может крестик закрытия попапа лучше чуть сдвинуть левее?
![screen shot 2017-08-05 at 12 01 32 pm](https://user-images.githubusercontent.com/17883276/28994406-363ca2e8-79d6-11e7-9541-7370715e9794.png)

**Comment by nicothin** [comment]
Без проблем, сдвинул (было 3 пикс от края экрана, стало 15)
(ширина скрола и учет ширины при отрисовке страницы зависит от ОС и настроек, в винде как скрол не закрывал эту кнопку, так и не закрывает )) )

**Comment by greeceruit** [comment]
В Ubuntu тоже ничего не закрывалось. В Chromium и FF

**Comment by nicothin** [comment]
оффтопик: есть статистика посещения по работающему ресурсу — сколько юзеров с убунтой?
у меня 75% — винда, 7% — маки, 3% — все линуксы, но это ресурс про IT и ЦА — Россия и русскоязычные, вроде Украины, Белоруссии и пр. бывших республик.

**Comment by greeceruit** [comment]
:) На старом greece.ru наверное я один с Линуксом. Но мы можем так перепутать причину со следствием. Например, у нового нашего сайта посещалка с дефолтного браузера андроида рано или поздно станет нулевой....

**Comment by nicothin** [comment]
оффтоп: да тут нет причин и следствий. Кроссбраузерность должна быть как можно более приближена к реальности среди ЦА.
Из старого хлама мы только IE10 и более старые выкинули.
