### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by vladimir075** [nicothin/greeceru#23]
Жень, можем ли на блоке менеджера 
![screen shot 2017-07-27 at 2 47 27 pm](https://user-images.githubusercontent.com/17883276/28668953-cda98e64-72da-11e7-9a64-4859661c9175.png)
вывести инфу какими языками владеет менеджер? сайт будет мультиязычный и вывод языков облегчит общение. Я бы сделал это под телефоном с надписью Spoken languages и флажками стран, хотя не знаю насколько пестрые флажки могут испортить дизайн. Если будут портить, то можно конечно и текстовым перечеслением. Место надо заложить под 4 языка максимум 
@Evgeniygavr

**Comment by Evgeniygavr** [comment]
Нет, так делать нельзя. Отстуствие общего языка (менеджер - юзер) будет стопорить пользователя. 

Допустим кейс: мне понравился объект, смотрю в карточку менеджера, а он/она не разговаривает "со мной на одном языке". Что мне делать? Отправлять просто запрос? То есть менеджер мне позвонит и мы будем "мычать" друг другу в трубку? Или меня наберет другой менеджер? А точно наберет другой? И таких вопросов я могу придумать еще с десяток.

Ситуации с "внутренней кухни" компании должны оставаться невидимыми для пользователя. Имею ввиду что если кто-то не владеет английским, то юзера должен обслужить другой менеджер. 

Сейчас же у клиента есть путь - объект, понравился, кнопка. Все, он больше ни о чем не думает.

**Comment by vladimir075** [comment]
Хорошо, принято. Вопрос снят.

**Comment by vladimir075** [comment]
У нас есть проблема в мобильной версии с загрузкой аватара юзера. В мобиле функция закрузки аватара имеется на странице Profile ЛК. Это страница на которую попадает юзер в ЛК по умолчанию и на которой показаны объекты недвижимости, которые занес юзер. 
![screen shot 2017-07-30 at 2 51 56 pm](https://user-images.githubusercontent.com/17883276/28753070-ac5d64f2-7536-11e7-9749-d243188700a1.png). Здесь все в порядке.
НО! Юзеры у нас делятся на тех, владельцев, которые занесли объект недвижимости на продажу или аренду и на тех кто например хочет купить или арендовать и соответственно у них нет занесенных объектов. Таким образом я предполагаю что по умолчанию можно отправлять последнюю категорию юзеров на другую страницу ЛК. Можно было бы в wish list, но опять таки не у всех в вишлисте будут объекты. Можно в savings...не знаю пока. 
Но в любом случае, куда бы их не отправлять, на всех других страницах возможности загрузки аватара в мобильной версии нет. 
Вообще я тут немного запутался. Ведь эта страница с объектами называется Profile. Соответственно у юзеров, у которых нет объектов, не будет страницы в ЛК с названием Profile?
@Evgeniygavr какие предложения относительно проблематики аватара для второй категории юзеров и по общему структурированию в рамках вышеизложенного?

**Comment by vladimir075** [comment]
http://www.nomesitis.gr/el/profile/savings/
думаю сюда внизу добавить кнопку Collect more drachmas (которая будет вести на страницу Add infrastructure point)

**Comment by vladimir075** [comment]
Николай, прошу сделать нам еще одно попап окно в общем нашем стиле с конпками да/нет.
Текст, внизу две кнопки да / нет, слева вверхе крестик закрытия попапа. Оно нам нужно, чтобы спрашивать дейстивтельно ли юзер хочет удалить объект например, хочет ли он добавить из compare в wish list при закрытии полосы compare. в макетах такого окна у нас нет.

**Comment by vladimir075** [comment]
Есть типы объектов, в которых вместо трех обязательных параметров, два или даже одно. Потому и в превью будет выводится соотвествующая инфа. @nicothin прошу сделать еще две вариации превью на базе вот этого
![screen shot 2017-08-05 at 12 27 37 pm](https://user-images.githubusercontent.com/17883276/28994565-c579bdf8-79d9-11e7-8e6c-019683b16e81.png)
1) в одной вариации линию, поделенную в примере выше на три раздела (вывод спален, ванных и общей площади там где 3, 3 и 120), поделить на две половины с одной разграничительной чертой вместо двух.
2) во второй вариации убрать разграничительную черту вообще, для вариантов, где будет выводиться только один параметр.

**Comment by nicothin** [comment]
Вариабельность кол-ва параметров объекта в пределах 1-3 уже была мной предусмотрена при верстке: http://take.ms/ZgBvF — скрин, где я просто вживую убрал из DOM два и один пункт списков.

Попап в ПН сделаю.

**Comment by vladimir075** [comment]
Николай, прошу внести небольшую поправку в страницу https://nicothin.github.io/greeceru/list-property-step-1.html
Мы решили на этом этапе разделить аренду на долгосрочную и сезонную, поэтому вместо двух имеющихся кнопок там нужны три. Sell property, Rent out long term, Rent out short term. Кнопки сделать побольше, чтобы уместилось и в переводах.
Думаю что и в десктопе надо делать кнопки одна под другой.
Если можно разместить рядом со второй и третьей кнопкой вопросик для хинта, то хорошо.

**Comment by nicothin** [comment]
>Николай, прошу сделать нам еще одно попап окно в общем нашем стиле с конпками да/нет.
Текст, внизу две кнопки да / нет, слева вверхе крестик закрытия попапа. Оно нам нужно, чтобы спрашивать дейстивтельно ли юзер хочет удалить объект например, хочет ли он добавить из compare в wish list при закрытии полосы compare. в макетах такого окна у нас нет.

добавлено на главной, в НПУ ткните ссылку confirm, чтобы посмотреть

>Мы решили на этом этапе разделить аренду на долгосрочную и сезонную, поэтому вместо двух имеющихся кнопок там нужны три. Sell property, Rent out long term, Rent out short term. Кнопки сделать побольше, чтобы уместилось и в переводах.

кнопку добавил, друг под другом на всех ширинах сделал, «or» выровнял.
ширины не менял, они там автоматически увеличатся, если в кнопке текст не влезет
добавил 2й и 3й кнопке иконки-подсказки. и вот с ними сложность: сейчас каждая такая кнопка — ссылка, на самом деле,  иконка же — внутри, то есть на мобилках тап по иконке обработается как тап по ссылке.
если сильно нужно там эти иконки иметь, могу сделать обертку, внутри которой спозиционирую иконку помощи в ВПУ кнопки-ссылки и вне ее (минут 10).

**Comment by vladimir075** [comment]
думаю, что эти тултипы подсказки надо сделать не в самих кнопках, а справа от них

**Comment by nicothin** [comment]
Вынес иконки из кнопок, разместил сбоку, отцентровав по вертикали.

**Comment by nicothin** [comment]
Продолжим обсуждать аватар в ишью про профиль, ибо речь о профиле.
https://github.com/nicothin/greeceru/issues/22#issuecomment-321370199 — отсюда.

**Comment by nicothin** [comment]
@vladimir075 
что-то не могу найти макета с попапом логина, который вы упоминали.
сделаю пока стандартными элементами форм.

**Comment by vladimir075** [comment]
@Evgeniygavr Жень, помоги пожалуйста найти Николаю попап логина

**Comment by nicothin** [comment]
Пока добавил на главную страницу попап логина (кликнуть по ссылке login в НПУ)

**Comment by vladimir075** [comment]
В моих макетах инвижн логин/ регистрация выглядят вот так.
https://projects.invisionapp.com/share/2MBJ7MQ68#/screens/235166903
https://projects.invisionapp.com/share/2MBJ7MQ68#/screens/235167046
Где они в макетах, надеюсь нам подскажет @Evgeniygavr

**Comment by nicothin** [comment]
Достаточно этих эскизов ))

**Comment by Evgeniygavr** [comment]
Макеты с логином, как и ранее, доступны в файле ui, pop-up.psd - https://goo.gl/n9Us2d

**Comment by nicothin** [comment]
@vladimir075 @greeceruit 
добавил на главную попапы Sign In и Sign Up

**Comment by vladimir075** [comment]
Благодарим

**Comment by vladimir075** [comment]
в мобильной версии при скроле попапов логина/регистрации иногда начинает скролиться сайт под ним

**Comment by nicothin** [comment]
Тут даже не знаю что предпринять — стилями я уже блокировал прокрутку в общем окне при открытом модальном окне... :(
По кр/ мере в эмуляции и на андроиде прокрутки страницы под модальным окном нет.
Есть особенность: видна сама страница при сокрытии панели управления мобильного браузера. Подумаю, можно ли что-то с этим сделать.

**Comment by vladimir075** [comment]
В попапах Sign In и Sign Up вместо значка В Контакте стоит значек мессенджера. прошу заменить на значек В Контакте

**Comment by nicothin** [comment]
Сделал механизм, корректирующий псевдоскролл на мобилках при открытом модальном окне в процессе браузерного сокрытия адресной строки. Для андроидов, по кр. мере, теперь не вижу казуса с показываемой «под модальным окном» страницей.

Иконку исправил.

**Comment by vladimir075** [comment]
@nicothin есть вопрос относительно иконок, которые мы добавили недавно.
![screen shot 2017-10-03 at 3 32 35 pm](https://user-images.githubusercontent.com/17883276/31125343-a6397956-a850-11e7-870f-87393697a0c6.png)
@greeceruit спрашивает куда их добавили, где их искать

**Comment by greeceruit** [comment]
@nicothin , мы хотим добавить несколько параметров в раздел "Основные параметры" карточки объекта недвижимости (страница вроде этой: http://www.nomesitis.gr/ru/property/639238751108-townhouse-viola-rent/ )
![nicothib-20171003-01](https://user-images.githubusercontent.com/29063417/31125841-6b0c7278-a852-11e7-8e78-dfbe61f6975b.png)

**Comment by nicothin** [comment]
@vladimir075 @greeceruit
https://nicothin.github.io/greeceru/img/sprite-svg.svg — все иконки в этой библотеке: http://take.ms/qFezo и у каждой свой ID
для вставки можно, к примеру:
```
<a href="" class="btn-icon">
  <svg width="18" height="18"
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="img/sprite-svg.svg#wish"></use>
  </svg>
</a>
```
(wish — ID нужной иконки, ссылка вокруг — только для стилизации заливки и реакции на наведение/фокус)

Но если место вставки какое-то специфическое, лучше скажите мне куда добавить, я добавлю.

**Comment by nicothin** [comment]
В «Основных параметрах» картинки добавлены фонами из стилей
Могу переделать так, чтобы можно было контролировать это из разметки, вставляя в нужные места что-то вроде
```
<svg width="18" height="18"
  <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="img/sprite-svg.svg#ИДЕНТИФИКАТОРКАРТИНКИВБИБЛИОТЕКЕ"></use>
</svg>
```
Делать?

**Comment by greeceruit** [comment]
@nicothin,  да, было бы супер сделать единый подход вставки иконок через id в спрайте. И нам было бы в дальнейшем добавлять новые параметры только через разметку, не трогая css

Много времени займёт? С моей стороны - почти совсем не займёт времени, если не затронет разметку родительского дива и будет реализовано, как сейчас, т.е. как список :) <ul>

Слово за @vladimir075

**Comment by nicothin** [comment]
Нет, времени займет не много, полчаса — максимум.
Разметка изменится только в одном плане: перед узлом текста добавится вставка svg с классом

**Comment by vladimir075** [comment]
ок, прошу сделать

**Comment by nicothin** [comment]
Переделал. Получилось совсем быстро, так что бесплатно :)
Изменениям подвергся файл с SVG-библиотекой, стилевой файл и, собственно, разметка: https://github.com/nicothin/greeceru/commit/583f2b3a2e767610461436e74b373f8d2263f605

**Comment by vladimir075** [comment]
Спасибо )

**Comment by vladimir075** [comment]
![screen shot 2017-10-08 at 12 49 59 pm](https://user-images.githubusercontent.com/17883276/31315747-477a7980-ac27-11e7-96c2-9606fa2e6c3d.png)
@nicothin, @greeceruit говорит, что не может найти последние добавленные иконки

**Comment by nicothin** [comment]
Хе... :(
Это я, значит, механизм переделал, а новые иконки не добавил.
Исправлено. Плюс добавил на https://nicothin.github.io/greeceru/internal-property.html демку этих присланных 7-и новых иконок.

**Comment by vladimir075** [comment]
Николай, я помню мы где то обсуждали проблематику с загрузкой аватара в ЛК. состояла она в том, что сам аватар и его загрузка появляется в разделе ЛК Profile, меж тем некоторые юзеры не попадают в этот раздел (например те, у кого не загружены объекты недвижимости) и в мобильной версии им просто негде загружать и смотреть свой аватар. Ты предлагал тогда решение, но кажется мы его не реализовали (если не ошибаюсь). Ты не помнишь где мы это обсуждали в гитхабе или может можешь найти? не знаю есть ли здесь какой-то инструмент для поиска по фразе.

**Comment by nicothin** [comment]
Признаться, помню лишь сам факт обсуждения :(
https://github.com/nicothin/greeceru/issues?utf8=%E2%9C%93&q=is%3Aissue%20%D0%B0%D0%B2%D0%B0%D1%82%D0%B0%D1%80%20 — тут есть поиск по ишью, это результаты поиска по открытым и закрытым ишью, слово аватар.

**Comment by greeceruit** [comment]
@nicothin На мобильных устройствах, например, на странице результатов поиска в map view при попытках скроллить карту одним пальцем, скроллится "подложка" под модальным окном. В этом ишью уже вроде бы этот момент обсуждался, и было найдено решение для андроида. В настоящий момент эффект проявляется и в андроид, и в iOS

С главным меню тот же эффект. При появлении модального окна с меню после нажатия на бургер, вместе с меню скроллится подложка. Тоже в обеих ОС

Не знаю, поможет это или нет, но css файл после последнего комита оказался сжатым. Может, прошёл комит со старой версии на каком-ить компе?

**Comment by nicothin** [comment]
@greeceruit 
https://nicothin.github.io/greeceru/index.html — не вижу скролла страницы
при открытии любого модального окна на body добавляется класс, блокирующий скролл.

**Comment by vladimir075** [comment]
Коль, посмотри пожалуйста на http://nomesitis.gr
У меня при открытии любого модального окна на сайте, сам сайт под ним скролируется. Открываю на айфоне 6. Это то, что мы сделали не действует или Олег что-то потерял в процессе?

**Comment by vladimir075** [comment]
Единственное что, об одном ли и том же мы говорим...

**Comment by vladimir075** [comment]
Скролиуется в рамках модальных окон. Как бы под модальным окном. Просто это мешает поведению.

**Comment by nicothin** [comment]
Открываю http://nomesitis.gr на андроиде, кликаю Войти, вижу мод. окно.
Скролл только в мод. окне.
Эмулирую ширину в devtools, всё то же — нет скролла, на body добавлен нужный класс.
Чуть позже смогу проверить на i-устройстве.

**Comment by nicothin** [comment]
Видимо, разные мод. окна тестируем?

**Comment by greeceruit** [comment]
Николай, а какой класс добавляется? Он добавляется к body или к какому-то div внутри body? Особенно явно эффект наблюдается на http://www.nomesitis.gr/en/search/rent/ в map view.

**Comment by vladimir075** [comment]
разные действительно почему то ведут себя по разному. Под "Войти" и у меня и в айфоне не скролируется. А вот например если открыть notice about price drop колокольчик, то видно что под ним скролируется. Также если и меню просто открыть основное.

**Comment by greeceruit** [comment]
Может, поможет как-то... https://youtu.be/lqWMEf8jsH4

**Comment by nicothin** [comment]
@greeceruit @vladimir075 
Да, вижу, что я тестил не в том месте.
Сегодня постараюсь разобраться.

**Comment by nicothin** [comment]
Стилями это полностью не решить, только JS-ом :(
Я добавил класс `.no-scroll`, который нужно дописывать/снимать на `body`, если не нужно блокировать скролл. 
Думаю, делать это нужно только на мобильных, т.к. на настольных в винде скролл виден постоянно и влияет на ширину вьюпорта (оригинальный бутстраповский механизм показа модальных окон подсчитывает его и добавляет на `body` инлайновый стиль с паддингом, идентичным ширине скролла).

Так же, я дописал строчку JS, чтобы этот класс переключался при открытии меню: https://github.com/nicothin/greeceru/commit/a90d7e0f396750d73ada188fc6eb719d8779fdec#diff-280fba1738bc2126e9950d3878edb949R8

**Comment by vladimir075** [comment]
Николай, а когда можно ожидать то, что я просил по взаимодействию карты и списка?

**Comment by nicothin** [comment]
Сделал
Пометка для @greeceruit 
Все карточки локаций имеют класс `card`. По наведению теперь показывается существенно более заметная тень. Чтобы фиксировать её на блоке (будет показана всегда, а не только по наведению), нужно дописать на блок класс-модификатор `card--active`.
Я сделал имеющиеся три картинки с пузырями в синем варианте. К примеру, `middle_label.svg` — обычный фон «пузыря», а `middle_label--blue.svg` — «пузырь с синим фоном.
Добавил файлы фонов «пузырей» в репозиторий:
```
src/img/middle_label--blue.svg
src/img/middle_label.svg
src/img/small_label--blue.svg
src/img/small_label.svg
src/img/wide_label--blue.svg
src/img/wide_label.svg
```
