### ISSUE TITLE
Страница Collect drachma

### ISSUE THREAD

**Issue by nicothin** [nicothin/greeceru#24]
@vladimir075
https://nicothin.github.io/greeceru/collect-drachma.html

**Comment by vladimir075** [comment]
1) Можно ли в мобильной версии оставлять аватары на карте (без кнопки рядом с ними)
2) Может в мобильной версии нам вынести нижнюю кнопку также вниз на весь экран, вместо подвала? (по аналогии как мы поступаем с другими страницами)
Других замечаний вроде нет

**Comment by nicothin** [comment]
1 сделано
2 сделано

через 5 мин развернется и можно смотреть

**Comment by vladimir075** [comment]
можно еще футер черный убрать?

**Comment by nicothin** [comment]
Можно, но тогда подвал пропадет и для бОльших ширин, я бы оставил (плюс не хочется делать новый вариант раскладки, который используется только на одной странице).
У нас есть раскладка, когда футера нет вовсе, но там есть причины: футер там отвлекает от главного действия, а тут футер есть или футера нет — разницы мало.

**Comment by vladimir075** [comment]
Хорошо, пусть будет так
