### ISSUE TITLE
Второй вариант форм логина и регистрации

### ISSUE THREAD

**Issue by vladimir075** [nicothin/greeceru#26]
Николай, вариант форм логина и регистрации, который был представлен в Макетах не отражает поведения при неверном/недостаточном вводе данных, плюс вообще на мой взгляд был не достаточно нами с Женей продуман. Поэтому я прошу сделать еще один вариант двух этих форм со всеми необходимыми поведениями согласно документу https://docs.google.com/document/d/1PdXoGbmstpY-VGtj07gWEsvzco5pvDvRLaMIh-GMcgI/edit
Чтобы не изобретать велосипед я взял за основу формы airbnb, и там где есть небольшие отклонения описал их в доке.
Сделать их только надо в нашем боевом раскрасе.

**Comment by nicothin** [comment]
Функциональность, проверки — все JS, который пишет @greeceruit (хотя я и написал немного JS, мелочи, типа табов, появления календаря и пр.)

Сделал модальное окно login (см. главную страницу, демки всех мод. окон — там). Показал там ошибочное состояние поля пароля (если убрать классы ошибки, будет виден «замок» в фоне поля ввода). Использовал по максимуму имеющиеся у нас компоненты. 

Сделал мод. окно reset-password (варианта размещения ссылка + кнопка в строку у нас нет, да и могут не влезть в узких модалках, так что ссылка Back to login сделана в подвале мод. окна)

Сделал мод. окно Log in to continue

Сделал мод. окно sign-up-2
