### ISSUE TITLE
Редизайн шапки

### ISSUE THREAD

**Issue by nicothin** [nicothin/greeceru#28]
https://monosnap.com/file/Mio4SvHpgNFMz55qT9vkvW85oPJjO2 — редизайн

1. Шапка страницы добавления, неясно что должно появляться при клике на https://monosnap.com/file/cUvJjp9t6VPnjMVBZdyy0UzsEfgEw0 и на https://monosnap.com/file/DVHzGoo28w8LfwGlNm0nIcVQC7dcV9 (этот элемент дублирован на разных ширинах вьюпорта).

2. Плохо смотрится https://monosnap.com/file/WOeTjscoYDxa5iGTiqVdvFJhKrkugH Шапка мобильного дизайна осталась прежней, это нормально? (большая кнопка из шапки просто пропадает на мобилке — это кажется странным)

3. На мобилке редизайн шапки (по кр. мере, для страницы добавления) убирает возможность авторизации. Это точно не нормально )) Пока размещу пункт для авторизации в боковом меню.

**Comment by nicothin** [comment]
>Шапка. Help center не отрисован в мобильной версии хедера (ниже) там где появляется лупа zpl://screen?pid=5c6d9867dd0ba39a1b3222cd&sid=5c6d9931ae27d83c11bf6df4. Думаю разместить там его надо будет справа от лупы в виде только значка вопроса. Не знаю поместится ли все на узких экранах мобильных.
Хорошо бы все таки поле поиска с лупой которое есть у нас на сайте оставить. Может слева от вопросика?

Есть задача на всех ширинах иметь возможность пользоваться поиском?

**Comment by nicothin** [comment]
@vladimir075 присоединяйтесь.

**Comment by nicothin** [comment]
>Шапка. Help center не отрисован в мобильной версии хедера (ниже) там где появляется лупа zpl://screen?pid=5c6d9867dd0ba39a1b3222cd&sid=5c6d9931ae27d83c11bf6df4. Думаю разместить там его надо будет справа от лупы в виде только значка вопроса. Не знаю поместится ли все на узких экранах мобильных.
Хорошо бы все таки поле поиска с лупой которое есть у нас на сайте оставить. Может слева от вопросика?

@vladimir075 Есть задача на всех ширинах иметь возможность пользоваться поиском?

**Comment by nicothin** [comment]
>1) Максимально до того уменьшения экрана, где все три элемента начинают не помещаться сохраняем в шапке справа от логотипа sign in, язык и кнопку List property for free. (Sign in нажатии на стрелку открывает попап форму логина, как сейчас. При этом учесть что в залогиненном варианте появляется аватар и имя со стрелкой)
>2) На ширинах экрана где все эти элементы начинают не помещаться, переносим язык в левое меню, как у нас и было. Так же в левое меню, где необходимо, переносим и List property for free. При этом ни его, ни язык предлагаю не прятать в допвыпадашку More, а разместить отдельно.
Таким образом Sign in у нас остается в шапке всегда, а остальные два уходят при необходимости в правое меню.

**Comment by vladimir075** [comment]
Николай, добрый вечер. Да, вижу что здесь небольшая путаница. Давайте сделаем так
1) Максимально до того уменьшения экрана, где все три элемента начинают не помещаться сохраняем в шапке справа от логотипа sign in, язык и кнопку List property for free. (Sign in нажатии на стрелку открывает попап форму логина, как сейчас. При этом учесть что в залогиненном варианте появляется аватар и имя со стрелкой)
2) На ширинах экрана где все эти элементы начинают не помещаться, переносим язык в левое меню, как у нас и было. Так же в левое меню, где необходимо, переносим и List property for free. При этом ни его, ни язык предлагаю не прятать в допвыпадашку More, а разместить отдельно.
Таким образом Sign in у нас остается в шапке всегда, а остальные два уходят при необходимости в правое меню.

**Comment by vladimir075** [comment]
> > Шапка. Help center не отрисован в мобильной версии хедера (ниже) там где появляется лупа zpl://screen?pid=5c6d9867dd0ba39a1b3222cd&sid=5c6d9931ae27d83c11bf6df4. Думаю разместить там его надо будет справа от лупы в виде только значка вопроса. Не знаю поместится ли все на узких экранах мобильных.
> > Хорошо бы все таки поле поиска с лупой которое есть у нас на сайте оставить. Может слева от вопросика?
> 
> @vladimir075 Есть задача на всех ширинах иметь возможность пользоваться поиском?

в принципе нет. Вопросик help center более важен. Хотя основное значение он имеет именно на страницах занесения объекта. Давайте предусмотрим help center только для страниц занесения объекта.

**Comment by nicothin** [comment]
@greeceruit Вопрос назрел: в процессе переделки новая версия сайта будет иметь одну ФС с нынешним? (Предусматривать полную обратную совместимость ценой оставления некоторого кол-ва уже ненужных стилей?)

**Comment by greeceruit** [comment]
> @greeceruit Вопрос назрел: в процессе переделки новая версия сайта будет иметь одну ФС с нынешним? (Предусматривать полную обратную совместимость ценой оставления некоторого кол-ва уже ненужных стилей?)

Да, наверное, старые стили нужно оставить. По двум причинам. 1) Некоторые вещи быстрее будет переделать сразу в продакшн. 2) Были сделаны вспомогательные инструменты для менеджеров с использованием старых классов. 

@nicothin, но если это касается только шапки, то старые стили можно и убрать, так как шапка на всех страницах одинаковая...

**Comment by nicothin** [comment]
@vladimir075 в предоставленном архиве с иконками нет части нужных: https://monosnap.com/file/y0MM7MkdfEhQjnvrKgeqyb2tpk1AIh 
https://monosnap.com/file/1Dd9D7W8G0JBymSAni4DZ6QX5EeSyh
Их же достать из макета в зеплине не получится.
Пока оставляю там пустые места. Если дизайнеры не предоставят, найду какие-либо похожие.

**Comment by nicothin** [comment]
@vladimir075 еще вопрос: как это должно работать? https://monosnap.com/file/fSMXg5tXS3c5VFsm6J0vsF6j4Ki4M5
По клику на стрелку назад что-то выезжает/скрывается?
Или просто меняется контентная область блока помощи?

**Comment by vladimir075** [comment]
Николай, я в отъезде на два дня, с мобильного как то плохо получается тут в гитхабе работать. По иконкам, затагте пожатуйста в вопросе Женю Гавриленко evgeniygavr@gmail.com, не получается у меня с мобильного.
По второму вопросу думаю просто меняется контентная часть

**Comment by nicothin** [comment]
Евгению написал.

**Comment by nicothin** [comment]
http://nicothin.pro/greeceru/add.html — задеплоил новую шапку и блок Центр помощи.
(правда, без иконок)

**Comment by vladimir075** [comment]
@nicothin Николай, вопрос по шапке. 1) У нас на узких экранах никак не получается оставить кнопку List property? 2) про лупу то что мы говорили. Она будет появляться только на карточке объекта? то есть для карточки объекта будет измененная шапка с лупой?

**Comment by nicothin** [comment]
http://nicothin.pro/greeceru/add.html — задеплоил новую шапку и блок Центр помощи. Теперь с иконками.

<hr>

>1) У нас на узких экранах никак не получается оставить кнопку List property?

если сократим текст внутри — с 480+ сможем:
![image](https://user-images.githubusercontent.com/3499680/54084002-57b3a300-433c-11e9-8851-c48952c0ad9f.png)

<hr>

>2) про лупу то что мы говорили. Она будет появляться только на карточке объекта? то есть для карточки объекта будет измененная шапка с лупой?

зависит от решения с кнопкой List property.
на 320 кнопку лупы девать откровенно некуда: 
![image](https://user-images.githubusercontent.com/3499680/54084098-87af7600-433d-11e9-9816-52cfec256445.png)

Вероятно, тут можно сделать два варианта шапки:

1. Шапка с help center и без поиска, который размещён в боковом меню (страницы добавления и, может, еще какие-то)
2. Шапка без help center, но с поиском (все прочие страницы)


Или, что проще, не показывать поиск на узких вьюпортах, всегда скрывая его внутри бокового меню.

**Comment by vladimir075** [comment]
В меню рядом с More у нас выпадашка. Она и была, сейчас не вижу.

**Comment by vladimir075** [comment]
В остальном пока предлагаю оставить как сейчас сверстано. Собственно говоря проблематика с лупой у нас появляется только на странице объекта, где в новом дизайне решили убрать поисковое поле сверху над слайдером, из за того что часть информации которая была под слайдером переместилась поверх его. (Правда с карточки объекта убрали и нижнюю кнопку Фильтр поиска...)
Давайте оставим пока шапку как сверстано, сверстаем карточку объекта и я потом еще раз все наглядно проанализирую.

**Comment by vladimir075** [comment]
@greeceruit прошу учесть, что Help Center с его вопросиком появляется в шапке только на стадии размещения объекта.

**Comment by nicothin** [comment]
Обсуждали в другой ишью: https://github.com/nicothin/greeceru/issues/33#issuecomment-477076868

Получается, есть два варианта новой «шапки»:

1. с поиском
2. с пунктом центра помощи

Предположительная функциональность:
На ширине 1170 (и более широких) нужно с помощью JS смореть помещаются ли текстовые пункты левой части меню в одну строку и, если не помещаются, прятать непоместившиеся под новый пункт «More». При этом пункт Contact Us всегда должен быть виден.
На ширине 1169 (и более узких) нужно выносить всё из пункта «More» (возвращать состояние меню без этого пункта).

@greeceruit @vladimir075 я правильно понимаю функциональность?

**Comment by greeceruit** [comment]
> @greeceruit @vladimir075 я правильно понимаю функциональность?


@nicothin   Про два варианта - верно. Подождём подтверждения от @vladimir075 

Отображение лупы или центра помощи, желательно, путём addClass / RemoveClass какого-нибудь модификатора. Занесение в More - я сейчас делаю просто путём перемещения пункта меню в другое место в DOM

**Comment by vladimir075** [comment]
да, про два варианта все верно

**Comment by nicothin** [comment]
http://nicothin.pro/greeceru/internal-property-3.html — шапка с поиском
http://nicothin.pro/greeceru/add.html — шапка с центром помощи

Отличие в разметке — на `header.page-header` в одном случае добавлен `page-header--search`, а в другом — `page-header--help-center`
Но я бы лучше выводил или не выводил сами DOM-узлы с поиском и ссылкой на центр помощи.

п.с.: пришлось для мобильных ширин вынести форму из шапки в контент страницы :(

**Comment by greeceruit** [comment]
> Но я бы лучше выводил или не выводил сами DOM-узлы с поиском и ссылкой на центр помощи.

Да, так и сделаю.

**Comment by vladimir075** [comment]
http://nicothin.pro/greeceru/add.html
Николай, сейчас только понял, что при нажатии на help center и выплывании окна, остальной экран у нас затемняется. А нам бы его оставить прозрачным, как был. Пример в скрине
![Screen Shot 2019-04-02 at 1 12 27 PM](https://user-images.githubusercontent.com/17883276/55395278-e84f5e80-5549-11e9-98f1-650411dcdf99.png)

**Comment by nicothin** [comment]
@vladimir075 готово
добавил тень от блока как в аналитике.

**Comment by vladimir075** [comment]
@nicothin отлично, спасибо

**Comment by greeceruit** [comment]
@nicothin, сразу после body на странице internal-property-3.html идёт div с классом page__inner  page__inner--has-bottom-btns. Модификатор page__inner--has-bottom-btns - это специфика карточки объекта или мне на все страницы его добавлять?

upd: нашёл этот модификатор и в старой вёрстке. Например, в личном кабинете. То есть ставлю только там, где он и был раньше. Если я не ошибаюсь, то вопрос снимается....

**Comment by nicothin** [comment]
@greeceruit класс-модификатор `page__inner--has-bottom-btns` нужен только на тех страницах, которые в мобильном представлении имеют прибитые книзу вьюпорта кнопки(у).
http://nicothin.pro/greeceru/internal-property-3.html имеет такую.
