### ISSUE TITLE
Редизайн блока в сайдбаре

### ISSUE THREAD

**Issue by nicothin** [nicothin/greeceru#31]
https://nicothin.pro/greeceru/mortgage.html

**Comment by greeceruit** [comment]
@nicothin, в сайдбаре желательно сделать не картинку, а iframe с видео. Можно будет это сделать?

**Comment by nicothin** [comment]
@greeceruit без проблем. Сегодня вечером сделаю пуш, в нем будет и коммит замены картинки на айфрейм.
Возможность использовать там картинку оставлю, конечно.

**Comment by nicothin** [comment]
Задеплоил.
