### ISSUE TITLE
Редизайн личного кабинета

### ISSUE THREAD

**Issue by nicothin** [nicothin/greeceru#34]
https://app.zeplin.io/project/5c6d9867dd0ba39a1b3222cd/dashboard

**Comment by nicothin** [comment]
https://docs.google.com/document/d/1LSX3PF3a_dm6VvIL-9e0vbVT01be74tCqwUlpJcEL7M/edit?ts=5cb858bd — соответствия

http://nicothin.pro/greeceru/profile-my-properties.html — последнее задеплоенное состояние.

**Comment by nicothin** [comment]
первое соответствие в первой карточке.
https://monosnap.com/file/QrFOpiaZ9zbSJfGGnLupaZyfATbMtx — второе и третье соответствие сделал для второй карточки. (на момент написания этого коммента не задеплоено)
Незначительные отклонения от макета вызваны использованием готовых элементов и нежеланием писать «Offer expired» в строке, где и так очень мало места и при переводе этого «Offer expired» всё могло бы сломаться, если словосочетание окажется длиннее.

**Comment by nicothin** [comment]
Задеплоил все 5 соответствий.

![image](https://user-images.githubusercontent.com/3499680/57197996-76b66600-6f76-11e9-83a6-0395ec7ac504.png)

**Comment by greeceruit** [comment]
@nicothin, у нас появился какой-то побочный эффект со стилями календарей после внедрения нового файла css. https://www.greece.ru/static/css/style.min.v-1.031.css

Такая картинка:
![Screenshot from 2019-05-12 14-16-50](https://user-images.githubusercontent.com/29063417/57581549-c7bbe200-74c1-11e9-868e-c0bc4914d27c.png)

Я попытался подключить предыдущий css https://www.greece.ru/static/css/style.min.v-1.030.css и эффект пропал
![Screenshot from 2019-05-12 14-15-03](https://user-images.githubusercontent.com/29063417/57581557-ea4dfb00-74c1-11e9-8dd3-d46df2a53144.png)

**Comment by vladimir075** [comment]
> Задеплоил все 5 соответствий.

у меня как то нажатие на первое соотвествие (верхнее) "промелькивает"

**Comment by nicothin** [comment]
@greeceruit вживую бы посмотреть на это. По скринам, боюсь, не разберусь :(

> у меня как то нажатие на первое соотвествие (верхнее) "промелькивает"

@vladimir075 нужно более подробное описание с указанием браузера и ОС. или можем созвониться в скайпе, покажете вживую.

**Comment by vladimir075** [comment]
Завтра спрошу еще у Олега, как у него, и если что созвонимся

**Comment by greeceruit** [comment]
> @greeceruit вживую бы посмотреть на это. По скринам, боюсь, не разберусь :(
> 

На любом объекте краткосрочной аренды. Если начать вводить даты и работать с календариком в виджете "Наличие мест и цены" 
Например, тут:
https://www.greece.ru/ru/property/500888151226-villa-prinos/

**Comment by nicothin** [comment]
Всё ясно. Название моего нового БЭМ-блока совпало с именем класса стороннего плагина :(
Поправлю.

**Comment by nicothin** [comment]
@greeceruit https://github.com/nicothin/greeceru/commit/211b213297ce978e9e2689946ded991c156f0080 — подправил с .checked (пришлось тронуть разметку в 2х местах)

@vladimir075 http://nicothin.pro/greeceru/profile-wishlist.html — соответствия вишлиста

**Comment by vladimir075** [comment]
Николай, в моем айфоне не нажимаются троеточия на фотке. Я так понимаю та же проблема с элементами на фотках осталась и в my properties. Что можем сделать?

**Comment by nicothin** [comment]
>Николай, в моем айфоне не нажимаются троеточия на фотке. Я так понимаю та же проблема с элементами на фотках осталась и в my properties. Что можем сделать?

Да, проблема, явно, того же рода.
Дело осложняется тем, что у меня на мобилке (андроид, айпад жены) это работает.
Вариант только один: переписать функциональность бутстраповского дропдауна. Причем лучше это сделать Олегу, у него JS лучше, чем у меня. :(

**Comment by vladimir075** [comment]
@greeceruit можем ли сделать и сколько это займет у тебя времени?
