### ISSUE TITLE
Рейтинг региона

### ISSUE THREAD

**Issue by vladimir075** [nicothin/greeceru#35]

**Comment by vladimir075** [comment]
@greeceruit Николай приступает к верстке модуля рейтинга регионов на основании документа https://docs.google.com/document/d/1BNFhUY30noHWwR6BHlj83nXRJ2_x8eq8Z1kGURJ3Zuw/edit?usp=sharing. Если есть какие-то вопросы програмно-технического характера от тебя, которые Николаю необходимо учесть, прошу изложить здесь.
@nicothin если будут вопросу к дизайнеру можно задавать их Надежде mavrmy@gmail.com

**Comment by nicothin** [comment]
@greeceruit https://www.figma.com/file/bT75RrRxZxONSZJ6Ei6jAZR9/Greece.test?node-id=51%3A0 — дизайнер предлагает вот такую штуку. Я пока её не пилю, мне нужно ваше мнение (какой-то пакет будете использовать для этого или сами будете писать? Если сами, то запилю сразу, если к-л готовое решение, то укажите какое, чтобы я стили сделал под него).

**Comment by greeceruit** [comment]
@nicothin , имеется в виду система рейтинга со звёздочками?

**Comment by nicothin** [comment]
@greeceruit нет, я про поиск региона (выпадуха с фильтрацией)

**Comment by greeceruit** [comment]
> @greeceruit нет, я про поиск региона (выпадуха с фильтрацией)

@nicothin , ещё не искал, какие готовые решения имеются. @vladimir075 , а сколько будет регионов? Если десятки-сотни, то можно их гуртом передавать во фронтэнд и осуществлять поиск на стороне клиента, а если тысячи или десятки тысяч, то, наверное, нужно придумывать какие-то ухищрения, чтобы не дёргать сервер на каждое нажатие клавиши. И в любом случае понадобится крутящееся колёсико при ожидании ответа сервера

**Comment by nicothin** [comment]
Срочности с выбором решения, я полагаю, нет.
Разумно использовать готовое. Я, значит, жду выбора решения и потом достилизовываю его до макетного вида.
Планирую сегодня доделать всё остальное, касающееся рейтинга.

**Comment by vladimir075** [comment]
@greeceruit  количество 325 (муниципалитетов)

**Comment by vladimir075** [comment]
@greeceruit если мой ответ о количестве помогает принять решение, о котором спрашивает Николай (просто не очень понимаю, о чем вы), хорошо ответить сразу, чтобы он мог доделать задачу.

**Comment by greeceruit** [comment]
@vladimir075 , в любом случае надо искать подходящее готовое решение

**Comment by nicothin** [comment]
Без этой штуки внизу:

http://nicothin.pro/greeceru/add-rating.html
http://nicothin.pro/greeceru/add-rating-success.html

**Comment by greeceruit** [comment]
Вот тут говорится о готовом на бутстрап 3. https://jsfiddle.net/KyleMit/9abm0hhy/ Но нам, наверное, не подходит, так как это выпадуха и доп. инпут для строки поиска, а нам ведь нужен инпут с функциональностью фильтрованного селекта.

**Comment by nicothin** [comment]
@greeceruit http://www.runningcoder.org/jquerytypeahead/demo/?country_v1%5Bquery%5D=af что-то такое нам нужно, похоже.

**Comment by greeceruit** [comment]
@nicothin , да, оно!

**Comment by nicothin** [comment]
@greeceruit посмотрите, устраивает ли по функционалу? Если да, его и внедрю через несколько часов.

**Comment by greeceruit** [comment]
@nicothin , с большой вероятностью подходит. И для варианта, когда все регионы уже есть при первом запросе, и для варианта, когда они подтягиваются ajax'ом.

**Comment by nicothin** [comment]
Внедряю.

**Comment by vladimir075** [comment]
@nicothin в айфоне у меня при нажатии не рожицу не работает переключение на следующий параметр оценки. Да и сам next не работает.
На карточке объекта сам рейтинг нам бы тоже не забыть )

**Comment by nicothin** [comment]
@vladimir075 http://nicothin.pro/greeceru/internal-property-3.html — для страницы локации я этот блок впилил.

А вот что делать с айфонами — не представляю :( 
Вслепую. 
Есть только одно предположение, со следующим деплоем придёт.

**Comment by nicothin** [comment]
http://nicothin.pro/greeceru/internal-property-3.html — рейтинг на стр. локации.
http://nicothin.pro/greeceru/add-rating.html — форма добавления.
http://nicothin.pro/greeceru/add-rating-success.html — сообщение об успехе.

Цвета, размеры и элементы управления, по возможности, использовал имеющиеся.

В дизайне два варианта финальной страницы, сделал тот, что кажется мне логичным.
Попробовал вслепую подправить поведение для айфона.

**Comment by vladimir075** [comment]
@nicothin У меня в айфоне продолжает не работать - 1) переход при нажатии на рожицу 2) сам линк Next 3) равно как и выпадашка при дропдауне при начале написания района (в десктопе начинает выпадать, то что там по умолчанию есть).
Я сходил в магаз попробовал на айфоне с версией 12.3.1 Там все работает. Так что видимо проблема у меня в айфоне со старой версией (9.3.2) Можем что-то сделать?
Еще вопрос не понял где искать финальную страницу. Ее нужны обе версии, одна только где фб шеринг и другая где и фб шеринг и приглашение рейтинговать. Это разные страницы, они появляются в разных местах.
![Screen Shot 2019-06-03 at 3 20 48 PM](https://user-images.githubusercontent.com/17883276/58801927-95ab2500-8614-11e9-81d2-8282e87d7322.png)

**Comment by nicothin** [comment]
@vladimir075 да, я тоже обнаружил, что в макете есть еще состояния успеха рейтингования. Не знаю зачем они (не понял дизайнера), но сверстал. Итого по этой задаче:

http://nicothin.pro/greeceru/internal-property-3.html — рейтинг на стр. локации.
http://nicothin.pro/greeceru/add-rating.html — форма добавления.
http://nicothin.pro/greeceru/add-rating-success.html — сообщение об успехе.
http://nicothin.pro/greeceru/add-rating-success-2.html — успех с призывом шарить
http://nicothin.pro/greeceru/add-rating-listing-submit.html — некий еще один успех

Про пути решения с iOS 9.3.2 думаю. Пока это для меня чёрный ящик. Ищу способ вывести ошибки как-то сразу на страницу, чтобы стало ясно хоть в какую сторону «копать».

**Comment by nicothin** [comment]
@vladimir075 я добавил на страницу http://nicothin.pro/greeceru/add-rating.html код, показывающий консольные сообщения/ошибки на самой странице. По умолчанию там снизу будет что-то вроде:

```
JQMIGRATE: Migrate is installed, version 3.0.1
Typeahead Initiated on undefined
```

Откройте ссылку с айфона, кликните по рейтингу, который не проставляется и скопипастьте вывод, если там вообще что-то появится.

**Comment by vladimir075** [comment]
JavaScript error: SyntaxError: Unexpected identifier 'num' on line 13687 for http://nicothin.pro/greeceru/js/script.min.js?1
JavaScript error: ReferenceError: Can't find variable: $ on line 943 for http://nicothin.pro/greeceru/add-rating.html

**Comment by vladimir075** [comment]
Прорыв )

**Comment by nicothin** [comment]
Хоть какие-то намёки на причины и способы решения, скорее.

**Comment by nicothin** [comment]
@vladimir075 прошу повторить процедуру проверки работоспособности. 
Посмотрим что ещё всплывёт. :(

**Comment by vladimir075** [comment]
Заработало. Правда иногда промелькивает, и перескакивает через одну карточку, но думаю что это уже после внедрения должно наладиться.
