### ISSUE TITLE
Последние правки перед утверждением главной страницы

### ISSUE THREAD

**Issue by vladimir075** [nicothin/greeceru#5]
@nicothin 
Николай, 
прошу сделать следующие правки
1) по скриншоту 
![0-weu-d3-698355167b6cfa4dc20dfb3dabc893a8](https://cloud.githubusercontent.com/assets/17883276/26580501/21e12f0e-4541-11e7-9e7d-d2ebbb565bea.jpg)

- Справа, где последний объект, должен быть отступ от края экрана. Такой же как и слева, перед первым объектом
2) в мобильных не должно быть tooltipов на иконках (сердечко и календарь). Все равно по тапу будет открываться попап
3) Мы внесли малеькие изменения в дизайн попап форм schedule, ask (добавилось поле сообщение) и interview (добавилось поле мейл. Прошу их сделать по последнему варианту
4) В попапе блог должна быть прокрутка статьи, вряд ли они туда будут помещаться без прокрутки. Также прошу переименовать сам модуль из blog в media, чтобы нам не путаться. У статьи блога будет другая механика.
@evgeniygavr, прошу отправить Николаю psd форм выше в последнем варианте (пункт 3)

**Comment by Evgeniygavr** [comment]
Обновил файл [ui, pop-up](https://drive.google.com/drive/folders/0B95Z4pk0Lfjgd09JeEhRaWIxREE?usp=sharing). Все модалки в нем.

**Comment by nicothin** [comment]
@vladimir075
>Справа, где последний объект, должен быть отступ от края экрана. Такой же как и слева, перед первым объектом

Увы, мне неизвестны карусели, которые умеют прикреплять слайды и к левому, и к правому краю.
Тут только если самописное что-то делать, но это уйма времени и сил ради незначительной фитчи.
Карусели же сейчас зациклены и «последнего слайда» просто нет. Неужто на айфоне не зациклены? (айпад зацикливает нормально)

2 ок, сделаю

3 ok, сделаю

4 скролл там есть, должен прокручиваться, если не влез (на айпаде скроллится). 
реальная видимость скролла зависит от ОС и ее настроек, я тут бессилен (не на всех можно показать скролл средствами css)
слово blog поменять могу, а вот блока blog у меня в разметке нет.

**Comment by vladimir075** [comment]
@nicothin 1. По первому было замечание старое, с внедрением карусели с отступами уже все в порядке.
Едиственное прошу остановить прокрутку карусели после 8ого слайда (чтобы она не была зацикленной)
4. ok
блог появится в разметке со следующими страницами )

**Comment by nicothin** [comment]
@vladimir075 
![image](https://cloud.githubusercontent.com/assets/3499680/26581806/0dd12dec-4547-11e7-92cd-0f60f0b2d277.png)
убрал зацикливание, на 768 (айпад, вертикаль) карусель останавливается с 2-мя видимыми слайдами (в плагине не регулируется сколько вписывающихся слайдов оставлять в конце, прибивать правый край, как у же писал, нельзя с этим плагином и я не знаю таких, с которыми можно :( ).

**Comment by vladimir075** [comment]
ок

**Comment by nicothin** [comment]
@vladimir075 
в новом файле с попапами вижу изменения в  schedule, ask — сейчас сделаю
там же добавились попапы sign in — их делать на этом этапе?

**Comment by vladimir075** [comment]
изменения добавились в schedule, ask и interview.Их прошу сделать сейчас. остальные на следующем этапе

**Comment by vladimir075** [comment]
а мои комменты приходят когда я упоминание не ставлю?

**Comment by nicothin** [comment]
>а мои комменты приходят когда я упоминание не ставлю?

это мой репозиторий, я автоматически подписан на все обновления ишью, так что мне — приходят.

**Comment by nicothin** [comment]
2 и 3 сделал
только поле ввода текста оставил то же, которое уже было (с белым фоном), а не с серым, как дорисовано, поскольку не вижу причин плодить сущности без надобности.
если надо иметь вариант с серым фоном поля ввода текста — скажите, сделаю.
![image](https://cloud.githubusercontent.com/assets/3499680/26582712/d0a0f1ec-454a-11e7-9c97-f3a17e18264a.png)

**Comment by vladimir075** [comment]
согласен. можно с белым

**Comment by Evgeniygavr** [comment]
Пардон, в модульных окнах оставляем "старый" вариант - с белым полем.

**Comment by nicothin** [comment]
тогда вопросы 1-4 закрыты
результат задеплоен, можно смотреть/проверять далее.

**Comment by vladimir075** [comment]
1) Последний вариант попапа interview у меня не отобразился
2) В айфоне 6 опять появилось горизонтальное скролирование самого основного экрана (мы это уже исправляли, видимо с добавлением карусели что- то сбилось
3) @Evgeniygavr Жень в мобильном макете, кторый ты предоставил Николаю блок media/feedback показывает кусок второго слайдера или нет? (по мне так можно в принципе на этом не заморачиваться (сейчас не показывает), но как скажешь.
И есть ли еще какие замечания, чтобы утвердить страницу?

**Comment by vladimir075** [comment]
![screen shot 2017-05-30 at 3 37 31 pm](https://cloud.githubusercontent.com/assets/17883276/26583481/1807a140-454e-11e7-89ce-b36996045f50.png)
то что в этом разрешении не появляется справа sign in, валюта и язык, это вопрос, который решается той закоментированной кнопкой more в меню, которую мы делали?

**Comment by nicothin** [comment]
Да, там кнопку и перемещение пунктов js-ом надо делать, кнопка в коде закомментирована, если раскомментить, то:
![image](https://cloud.githubusercontent.com/assets/3499680/26583627/a77d64c2-454e-11e7-9f96-20e8c7dac0f2.png)

**Comment by nicothin** [comment]
с гор. строллом в айфоне беда какая-то — не могу эмулировать.
точно нет масштабирования перед скроллом?

**Comment by vladimir075** [comment]
ок. 
@greeceruit, прошу принять во внимание предыдущий скриншот Николая по внешнему виду механики кнопки more в меню для дальнейшей работы когда дойдет до дела
в мобиле при попытке введения адреса в соотвествующий фильтр появляется клавиатура и экран зумируется. Логидзе. Но при нажатии done на клавиатуре, экран не возвращается к начальному разрешению. Это нормально и ли надо что-то подправить?

**Comment by nicothin** [comment]
это устройство само решает масштабировать
«лечится» только полным отключением зума на странице или временным отключением зума по получению полем фокуса (второе ни разу не пробовал).

**Comment by vladimir075** [comment]
вот сейчас нормально. перестало скролироваться. И feed back/media правильно встал

**Comment by nicothin** [comment]
а я ничего для этого не предпринимал ))

**Comment by vladimir075** [comment]
чудеса ))

**Comment by nicothin** [comment]
interview с доп. полем задеплоился

**Comment by vladimir075** [comment]
да увидел

**Comment by Evgeniygavr** [comment]
Последнее замечание - скругление углов у выпадающих элементов и модальных окнах. Везде должен быть border-radius: 2px.

**Comment by Evgeniygavr** [comment]
Николай, реализуйте еще, пожалуйста, ховер на карточках объектов - в макете home page [hovers]. [Здесь скрин](http://i.piccy.info/i9/c4af9a1045771580f2bb856b931de60c/1496151431/79276/1150034/Bez_ymeny_2.jpg) и если можно, то не делать ховер на цене и иконках. Только при наведении на фото и область с названием, как Вы уже сделали (стрелочка заменяется на руку с пальнем :) )

**Comment by nicothin** [comment]
Подправил бордюры для карточки объекта и для модальных окон. У прочих, насколько вижу, есть сглаживание углов в 2 пикс.
По ховеру: наведение на все, кроме строки с ценой и иконками должно приводить к появлению тени под карточкой?

**Comment by Evgeniygavr** [comment]
Да, бордер в 2 пикселя я использовал везде: инпуты, формы, модальные окна, выпадающие элементы, карточки объекта и статей.

По ховеру - да, если такое возможно, но хотелось бы глянуть в динамике. Если будет смотреться "как-то странно", то лучше оставить ховер на всю карточку.

**Comment by nicothin** [comment]
Это относительно трудоемко — переделать так, чтобы было возможно отлавливать ховер «на всем, кроме». Добавил по наведению на всю карточку.

Скругления еще нашел где не сделал — на дропах главной менюхи. Добавил, через пару минут появится.

**Comment by Evgeniygavr** [comment]
Ок, отлично.

**Comment by Evgeniygavr** [comment]
Николай, а можем еще в мобильной версии вернуть иконку "подписка на цену"? Я не досмотрел и убрал ее. Или если Вы уже закончили работу, то потом позже ее добавить можно.

**Comment by nicothin** [comment]
Не знаю))
Покажите о чем речь с помощью скриншота.

**Comment by Evgeniygavr** [comment]
Вот здесь, между "сердчеком" и "календариком" я потерял, каюсь, иконку колокольчика. [Скрин ](http://piccy.info/view3/11240533/43d66f16e8e4dcf48f684fcdfe172512/)

**Comment by nicothin** [comment]
![image](https://cloud.githubusercontent.com/assets/3499680/26638666/541fe632-462b-11e7-8445-e3f9bddd086d.png)
тогда при большой цене съема есть риск не влезть в строку.
как там будем переполнять? могу в блоке цены скрывать не влезающее за многоточием.

**Comment by Evgeniygavr** [comment]
Да, уже про цену подумал, что есть вариант не влезть. Так, а если мы наши иконки скроем в "троеточие"? Скажем, от разрешение 320 до 768 показывать три точки, а дальше иконочки. [Скрин ](http://piccy.info/view3/11240710/895ced2f36097797e21fa84ee1c1a4f2/)  И скажите, пожалуйста, свой взгляд со стороны - что думаете о таком решении ?

**Comment by nicothin** [comment]
да, в целом, нормальное решение иметь такой дроп на мобилках. это минут на 20 работы.
есть и вариант побыстрее: разнести цену и ряд с иконками по строкам — цену в верхней строке, под ней ряд с иконками ))

**Comment by Evgeniygavr** [comment]
Хороший вариант, но у нас везде иконки справа. В Вашем примере придется их сделать, я так предполагаю, с выключкой по левому краю. Давайте поступим так, чтобы я Вас не мучил, пока что этот момент оставим, а когда будет вот этих "20 минут" свободных так и сделаем, чтобы моя дизайнерская душа была спокойна.

**Comment by nicothin** [comment]
Вынес отдельно, чтобы не забыть
