### ISSUE TITLE
Проверка на разных устройствах.

### ISSUE THREAD

**Issue by vladimir075** [nicothin/greeceru#6]
@nicothin , беспокоит такой вопрос. Как осуществляется проверка отображения верстки на разных устройствах. Возьмем тот же глюк отображения слайдера к примеру. Я открыл в шестом афоне и увидел проблему. Но у меня нет разных телефонов, например тогоже андроида итд, или разных моделей. И мне сложно проверить есть ли какие то проблемы с отображением верстки на разных устройствах? Как подобная проверка Вами осуществляется?

**Comment by nicothin** [comment]
На адероиде проверяю на реальном телефоне и на планшете.
Мобильный Айос — на айпаде проверяю.
Браузеры под виндой — комп с виндой.
Настольный OSX — макбук эйр ))

В отсутствие устройств — есть сервисы в сети для проверки
кроссбраузерности. https://www.browserstack.com/ — пример.
Или можно на виртуальыне машины ставить целевые ОСи, браузеры и проверять.
